(******************************************************************************)
(*  GENERATED by tools/gen_coq.py -- do not edit by hand.                     *)
(*  Source: data/fossils.json (sourced literature record; see its evidence fields)*)
(******************************************************************************)

From Coq Require Import List String.
From Sciuridae Require Import Lib.Base Data.Geography Data.Taxonomy.
Import ListNotations.
Local Open Scope string_scope.

(* Fossil genera are a separate type: they are not part of the MDD species
   list, and nothing about extant squirrels is inferred from them. *)
(* Fossil sciurid genera. *)
Inductive FossilGenus : Type :=
| Douglassciurus
| Hesperopetes
| Palaeosciurus
| Protosciurus.

Definition fossil_index (x : FossilGenus) : nat :=
  match x with
  | Douglassciurus => 0
  | Hesperopetes => 1
  | Palaeosciurus => 2
  | Protosciurus => 3
  end.

Definition fossil_table : list FossilGenus := [
  Douglassciurus; Hesperopetes; Palaeosciurus; Protosciurus].

Lemma fossil_table_index : forall x, nth_error fossil_table (fossil_index x) = Some x.
Proof. solve_table_index. Qed.

Lemma fossil_indices : map fossil_index fossil_table = seq 0 (List.length fossil_table).
Proof. vm_compute. reflexivity. Qed.

#[export] Instance Beq_FossilGenus : Beq FossilGenus :=
  {| beq := table_beq FossilGenus fossil_index;
     beq_spec := table_beq_spec FossilGenus fossil_index fossil_table fossil_table_index |}.

#[export] Instance Finite_FossilGenus : Finite FossilGenus :=
  {| enum := fossil_table;
     enum_complete := table_complete FossilGenus fossil_index fossil_table fossil_table_index;
     enum_nodup := table_nodup FossilGenus fossil_index fossil_table fossil_indices |}.

Definition fossil_name (x : FossilGenus) : string :=
  match x with
  | Douglassciurus => "Douglassciurus"
  | Hesperopetes => "Hesperopetes"
  | Palaeosciurus => "Palaeosciurus"
  | Protosciurus => "Protosciurus"
  end.
Inductive Material : Type := Skeleton | SkullAndTeeth | TeethAndLimbBones | TeethOnly.

(* A published opinion on where a fossil genus belongs. *)
Inductive Opinion : Type :=
| Stem                          (* outside crown Sciuridae *)
| IncertaeSedis                 (* in Sciuridae (crown or stem), unplaced *)
| InSubfamilyOp : Subfamily -> Opinion
| InTribeOp : Tribe -> Opinion
| StemOfTribe : Tribe -> Opinion.  (* on the lineage leading to a tribe *)

(* Ages are in units of 0.01 Ma, written (youngest, oldest). *)
Record FossilInfo : Type := {
  type_species : string;
  fossil_continents : list Continent;
  material : Material;
  gliding_evidence : bool;
  genus_range : nat * nat;          (* first to last appearance *)
  oldest_dated : nat * nat;         (* the oldest reliably dated occurrence *)
  placements : list (Opinion * string)
}.

Definition fossil_info (f : FossilGenus) : FossilInfo :=
  match f with
  | Douglassciurus => {| type_species := "Douglassciurus jeffersoni (Douglass, 1901)";
      fossil_continents := [North_America]; material := Skeleton; gliding_evidence := false;
      genus_range := (2950, 4103); oldest_dated := (3580, 3660);
      placements := [(Stem, "Casanovas-Vilar et al. 2018 (most basal sciurid; 'not a Sciurinae')"); (InSubfamilyOp Sciurinae, "Korth 2014 (Paleobiology Database opinion); Li et al. 2023 list it among Sciurinae")] |}
  | Hesperopetes => {| type_species := "Hesperopetes thoringtoni Emry & Korth, 2007";
      fossil_continents := [North_America]; material := TeethOnly; gliding_evidence := false;
      genus_range := (2950, 3700); oldest_dated := (3580, 3660);
      placements := [(IncertaeSedis, "Emry & Korth 2007 (not assigned to a subfamily); Casanovas-Vilar et al. 2018"); (StemOfTribe Pteromyini, "Emry & Korth 2007: may represent the earliest occurrence of the lineage leading to flying squirrels")] |}
  | Palaeosciurus => {| type_species := "Palaeosciurus feignouxi Pomel, 1853";
      fossil_continents := [Europe; Asia]; material := TeethAndLimbBones; gliding_evidence := false;
      genus_range := (1163, 3390); oldest_dated := (2730, 3390);
      placements := [(IncertaeSedis, "Casanovas-Vilar et al. 2018 (lacks diagnostic features of any extant group); McKenna & Bell 1997"); (InSubfamilyOp Sciurinae, "Li et al. 2023 (tree-squirrel morphotype, listed under Sciurinae)"); (InSubfamilyOp Xerinae, "Vianey-Liaud 1974, 1975 ('ecureuil terrestre', ground squirrel from limb proportions)")] |}
  | Protosciurus => {| type_species := "Protosciurus condoni Black, 1963";
      fossil_continents := [North_America]; material := SkullAndTeeth; gliding_evidence := false;
      genus_range := (1250, 3700); oldest_dated := (2303, 3390);
      placements := [(InTribeOp Sciurini, "Black 1963 (Tribe Sciurini: Sciurus, Miosciurus, Protosciurus); Paleobiology Database parent"); (Stem, "Casanovas-Vilar et al. 2018 ('better regarded as stem sciurids')")] |}
  end.
