(******************************************************************************)
(*  GENERATED by tools/gen_coq.py -- do not edit by hand.                     *)
(*  Source: MDD v2.5 vocabularies (continents, realms, IUCN); countries used by Sciuridae*)
(******************************************************************************)

From Coq Require Import List String.
From Sciuridae Require Import Lib.Base.
Import ListNotations.
Local Open Scope string_scope.

(* Continents, in the vocabulary of MDD v2.5 (continentDistribution). *)
Inductive Continent : Type :=
| Africa
| Antarctica
| Asia
| Europe
| North_America
| Oceania
| South_America.

Definition continent_index (x : Continent) : nat :=
  match x with
  | Africa => 0
  | Antarctica => 1
  | Asia => 2
  | Europe => 3
  | North_America => 4
  | Oceania => 5
  | South_America => 6
  end.

Definition continent_table : list Continent := [
  Africa; Antarctica; Asia; Europe; North_America; Oceania;
  South_America].

Lemma continent_table_index : forall x, nth_error continent_table (continent_index x) = Some x.
Proof. solve_table_index. Qed.

Lemma continent_indices : map continent_index continent_table = seq 0 (List.length continent_table).
Proof. vm_compute. reflexivity. Qed.

#[export] Instance Beq_Continent : Beq Continent :=
  {| beq := table_beq Continent continent_index;
     beq_spec := table_beq_spec Continent continent_index continent_table continent_table_index |}.

#[export] Instance Finite_Continent : Finite Continent :=
  {| enum := continent_table;
     enum_complete := table_complete Continent continent_index continent_table continent_table_index;
     enum_nodup := table_nodup Continent continent_index continent_table continent_indices |}.

Definition continent_name (x : Continent) : string :=
  match x with
  | Africa => "Africa"
  | Antarctica => "Antarctica"
  | Asia => "Asia"
  | Europe => "Europe"
  | North_America => "North America"
  | Oceania => "Oceania"
  | South_America => "South America"
  end.
(* Biogeographic realms, in the vocabulary of MDD v2.5 (biogeographicRealm). *)
Inductive Realm : Type :=
| Afrotropic
| Antarctic
| Australasia
| Indomalaya
| Nearctic
| Neotropic
| Oceanian
| Palearctic.

Definition realm_index (x : Realm) : nat :=
  match x with
  | Afrotropic => 0
  | Antarctic => 1
  | Australasia => 2
  | Indomalaya => 3
  | Nearctic => 4
  | Neotropic => 5
  | Oceanian => 6
  | Palearctic => 7
  end.

Definition realm_table : list Realm := [
  Afrotropic; Antarctic; Australasia; Indomalaya; Nearctic; Neotropic;
  Oceanian; Palearctic].

Lemma realm_table_index : forall x, nth_error realm_table (realm_index x) = Some x.
Proof. solve_table_index. Qed.

Lemma realm_indices : map realm_index realm_table = seq 0 (List.length realm_table).
Proof. vm_compute. reflexivity. Qed.

#[export] Instance Beq_Realm : Beq Realm :=
  {| beq := table_beq Realm realm_index;
     beq_spec := table_beq_spec Realm realm_index realm_table realm_table_index |}.

#[export] Instance Finite_Realm : Finite Realm :=
  {| enum := realm_table;
     enum_complete := table_complete Realm realm_index realm_table realm_table_index;
     enum_nodup := table_nodup Realm realm_index realm_table realm_indices |}.

Definition realm_name (x : Realm) : string :=
  match x with
  | Afrotropic => "Afrotropic"
  | Antarctic => "Antarctic"
  | Australasia => "Australasia"
  | Indomalaya => "Indomalaya"
  | Nearctic => "Nearctic"
  | Neotropic => "Neotropic"
  | Oceanian => "Oceania"
  | Palearctic => "Palearctic"
  end.
(* The 144 countries in which MDD v2.5 records a native sciurid. *)
Inductive Country : Type :=
| Afghanistan
| Albania
| Algeria
| Angola
| Argentina
| Armenia
| Austria
| Azerbaijan
| Bangladesh
| Belarus
| Belgium
| Belize
| Benin
| Bhutan
| Bolivia
| Bosnia_and_Herzegovina
| Botswana
| Brazil
| Brunei
| Bulgaria
| Burkina_Faso
| Burundi
| Cambodia
| Cameroon
| Canada
| Central_African_Republic
| Chad
| China
| Colombia
| Costa_Rica
| Cote_d_Ivoire
| Croatia
| Czech_Republic
| Democratic_Republic_of_the_Congo
| Denmark
| Djibouti
| Ecuador
| El_Salvador
| Equatorial_Guinea
| Eritrea
| Estonia
| Ethiopia
| Finland
| France
| French_Guiana
| Gabon
| Gambia
| Georgia
| Germany
| Ghana
| Greece
| Guatemala
| Guinea
| Guinea_Bissau
| Guyana
| Honduras
| Hungary
| India
| Indonesia
| Iran
| Iraq
| Ireland
| Israel
| Italy
| Japan
| Jordan
| Kazakhstan
| Kenya
| Kosovo
| Kyrgyzstan
| Laos
| Latvia
| Lebanon
| Lesotho
| Liberia
| Liechtenstein
| Lithuania
| Luxembourg
| Malawi
| Malaysia
| Mali
| Mauritania
| Mexico
| Moldova
| Mongolia
| Montenegro
| Morocco
| Mozambique
| Myanmar
| Namibia
| Nepal
| Netherlands
| Nicaragua
| Niger
| Nigeria
| North_Korea
| North_Macedonia
| Norway
| Pakistan
| Palestine
| Panama
| Paraguay
| Peru
| Philippines
| Poland
| Portugal
| Republic_of_the_Congo
| Romania
| Russia
| Rwanda
| Senegal
| Serbia
| Sierra_Leone
| Singapore
| Slovakia
| Slovenia
| Somalia
| South_Africa
| South_Korea
| South_Sudan
| Spain
| Sri_Lanka
| Sudan
| Suriname
| Sweden
| Switzerland
| Syria
| Taiwan
| Tajikistan
| Tanzania
| Thailand
| Togo
| Trinidad_and_Tobago
| Turkey
| Turkmenistan
| Uganda
| Ukraine
| United_Kingdom
| United_States
| Uzbekistan
| Venezuela
| Vietnam
| Zambia
| Zimbabwe.

Definition country_index (x : Country) : nat :=
  match x with
  | Afghanistan => 0
  | Albania => 1
  | Algeria => 2
  | Angola => 3
  | Argentina => 4
  | Armenia => 5
  | Austria => 6
  | Azerbaijan => 7
  | Bangladesh => 8
  | Belarus => 9
  | Belgium => 10
  | Belize => 11
  | Benin => 12
  | Bhutan => 13
  | Bolivia => 14
  | Bosnia_and_Herzegovina => 15
  | Botswana => 16
  | Brazil => 17
  | Brunei => 18
  | Bulgaria => 19
  | Burkina_Faso => 20
  | Burundi => 21
  | Cambodia => 22
  | Cameroon => 23
  | Canada => 24
  | Central_African_Republic => 25
  | Chad => 26
  | China => 27
  | Colombia => 28
  | Costa_Rica => 29
  | Cote_d_Ivoire => 30
  | Croatia => 31
  | Czech_Republic => 32
  | Democratic_Republic_of_the_Congo => 33
  | Denmark => 34
  | Djibouti => 35
  | Ecuador => 36
  | El_Salvador => 37
  | Equatorial_Guinea => 38
  | Eritrea => 39
  | Estonia => 40
  | Ethiopia => 41
  | Finland => 42
  | France => 43
  | French_Guiana => 44
  | Gabon => 45
  | Gambia => 46
  | Georgia => 47
  | Germany => 48
  | Ghana => 49
  | Greece => 50
  | Guatemala => 51
  | Guinea => 52
  | Guinea_Bissau => 53
  | Guyana => 54
  | Honduras => 55
  | Hungary => 56
  | India => 57
  | Indonesia => 58
  | Iran => 59
  | Iraq => 60
  | Ireland => 61
  | Israel => 62
  | Italy => 63
  | Japan => 64
  | Jordan => 65
  | Kazakhstan => 66
  | Kenya => 67
  | Kosovo => 68
  | Kyrgyzstan => 69
  | Laos => 70
  | Latvia => 71
  | Lebanon => 72
  | Lesotho => 73
  | Liberia => 74
  | Liechtenstein => 75
  | Lithuania => 76
  | Luxembourg => 77
  | Malawi => 78
  | Malaysia => 79
  | Mali => 80
  | Mauritania => 81
  | Mexico => 82
  | Moldova => 83
  | Mongolia => 84
  | Montenegro => 85
  | Morocco => 86
  | Mozambique => 87
  | Myanmar => 88
  | Namibia => 89
  | Nepal => 90
  | Netherlands => 91
  | Nicaragua => 92
  | Niger => 93
  | Nigeria => 94
  | North_Korea => 95
  | North_Macedonia => 96
  | Norway => 97
  | Pakistan => 98
  | Palestine => 99
  | Panama => 100
  | Paraguay => 101
  | Peru => 102
  | Philippines => 103
  | Poland => 104
  | Portugal => 105
  | Republic_of_the_Congo => 106
  | Romania => 107
  | Russia => 108
  | Rwanda => 109
  | Senegal => 110
  | Serbia => 111
  | Sierra_Leone => 112
  | Singapore => 113
  | Slovakia => 114
  | Slovenia => 115
  | Somalia => 116
  | South_Africa => 117
  | South_Korea => 118
  | South_Sudan => 119
  | Spain => 120
  | Sri_Lanka => 121
  | Sudan => 122
  | Suriname => 123
  | Sweden => 124
  | Switzerland => 125
  | Syria => 126
  | Taiwan => 127
  | Tajikistan => 128
  | Tanzania => 129
  | Thailand => 130
  | Togo => 131
  | Trinidad_and_Tobago => 132
  | Turkey => 133
  | Turkmenistan => 134
  | Uganda => 135
  | Ukraine => 136
  | United_Kingdom => 137
  | United_States => 138
  | Uzbekistan => 139
  | Venezuela => 140
  | Vietnam => 141
  | Zambia => 142
  | Zimbabwe => 143
  end.

Definition country_table : list Country := [
  Afghanistan; Albania; Algeria; Angola; Argentina; Armenia;
  Austria; Azerbaijan; Bangladesh; Belarus; Belgium; Belize;
  Benin; Bhutan; Bolivia; Bosnia_and_Herzegovina; Botswana; Brazil;
  Brunei; Bulgaria; Burkina_Faso; Burundi; Cambodia; Cameroon;
  Canada; Central_African_Republic; Chad; China; Colombia; Costa_Rica;
  Cote_d_Ivoire; Croatia; Czech_Republic; Democratic_Republic_of_the_Congo; Denmark; Djibouti;
  Ecuador; El_Salvador; Equatorial_Guinea; Eritrea; Estonia; Ethiopia;
  Finland; France; French_Guiana; Gabon; Gambia; Georgia;
  Germany; Ghana; Greece; Guatemala; Guinea; Guinea_Bissau;
  Guyana; Honduras; Hungary; India; Indonesia; Iran;
  Iraq; Ireland; Israel; Italy; Japan; Jordan;
  Kazakhstan; Kenya; Kosovo; Kyrgyzstan; Laos; Latvia;
  Lebanon; Lesotho; Liberia; Liechtenstein; Lithuania; Luxembourg;
  Malawi; Malaysia; Mali; Mauritania; Mexico; Moldova;
  Mongolia; Montenegro; Morocco; Mozambique; Myanmar; Namibia;
  Nepal; Netherlands; Nicaragua; Niger; Nigeria; North_Korea;
  North_Macedonia; Norway; Pakistan; Palestine; Panama; Paraguay;
  Peru; Philippines; Poland; Portugal; Republic_of_the_Congo; Romania;
  Russia; Rwanda; Senegal; Serbia; Sierra_Leone; Singapore;
  Slovakia; Slovenia; Somalia; South_Africa; South_Korea; South_Sudan;
  Spain; Sri_Lanka; Sudan; Suriname; Sweden; Switzerland;
  Syria; Taiwan; Tajikistan; Tanzania; Thailand; Togo;
  Trinidad_and_Tobago; Turkey; Turkmenistan; Uganda; Ukraine; United_Kingdom;
  United_States; Uzbekistan; Venezuela; Vietnam; Zambia; Zimbabwe].

Lemma country_table_index : forall x, nth_error country_table (country_index x) = Some x.
Proof. solve_table_index. Qed.

Lemma country_indices : map country_index country_table = seq 0 (List.length country_table).
Proof. vm_compute. reflexivity. Qed.

#[export] Instance Beq_Country : Beq Country :=
  {| beq := table_beq Country country_index;
     beq_spec := table_beq_spec Country country_index country_table country_table_index |}.

#[export] Instance Finite_Country : Finite Country :=
  {| enum := country_table;
     enum_complete := table_complete Country country_index country_table country_table_index;
     enum_nodup := table_nodup Country country_index country_table country_indices |}.

Definition country_name (x : Country) : string :=
  match x with
  | Afghanistan => "Afghanistan"
  | Albania => "Albania"
  | Algeria => "Algeria"
  | Angola => "Angola"
  | Argentina => "Argentina"
  | Armenia => "Armenia"
  | Austria => "Austria"
  | Azerbaijan => "Azerbaijan"
  | Bangladesh => "Bangladesh"
  | Belarus => "Belarus"
  | Belgium => "Belgium"
  | Belize => "Belize"
  | Benin => "Benin"
  | Bhutan => "Bhutan"
  | Bolivia => "Bolivia"
  | Bosnia_and_Herzegovina => "Bosnia and Herzegovina"
  | Botswana => "Botswana"
  | Brazil => "Brazil"
  | Brunei => "Brunei"
  | Bulgaria => "Bulgaria"
  | Burkina_Faso => "Burkina Faso"
  | Burundi => "Burundi"
  | Cambodia => "Cambodia"
  | Cameroon => "Cameroon"
  | Canada => "Canada"
  | Central_African_Republic => "Central African Republic"
  | Chad => "Chad"
  | China => "China"
  | Colombia => "Colombia"
  | Costa_Rica => "Costa Rica"
  | Cote_d_Ivoire => "Cote d'Ivoire"
  | Croatia => "Croatia"
  | Czech_Republic => "Czech Republic"
  | Democratic_Republic_of_the_Congo => "Democratic Republic of the Congo"
  | Denmark => "Denmark"
  | Djibouti => "Djibouti"
  | Ecuador => "Ecuador"
  | El_Salvador => "El Salvador"
  | Equatorial_Guinea => "Equatorial Guinea"
  | Eritrea => "Eritrea"
  | Estonia => "Estonia"
  | Ethiopia => "Ethiopia"
  | Finland => "Finland"
  | France => "France"
  | French_Guiana => "French Guiana"
  | Gabon => "Gabon"
  | Gambia => "Gambia"
  | Georgia => "Georgia"
  | Germany => "Germany"
  | Ghana => "Ghana"
  | Greece => "Greece"
  | Guatemala => "Guatemala"
  | Guinea => "Guinea"
  | Guinea_Bissau => "Guinea-Bissau"
  | Guyana => "Guyana"
  | Honduras => "Honduras"
  | Hungary => "Hungary"
  | India => "India"
  | Indonesia => "Indonesia"
  | Iran => "Iran"
  | Iraq => "Iraq"
  | Ireland => "Ireland"
  | Israel => "Israel"
  | Italy => "Italy"
  | Japan => "Japan"
  | Jordan => "Jordan"
  | Kazakhstan => "Kazakhstan"
  | Kenya => "Kenya"
  | Kosovo => "Kosovo"
  | Kyrgyzstan => "Kyrgyzstan"
  | Laos => "Laos"
  | Latvia => "Latvia"
  | Lebanon => "Lebanon"
  | Lesotho => "Lesotho"
  | Liberia => "Liberia"
  | Liechtenstein => "Liechtenstein"
  | Lithuania => "Lithuania"
  | Luxembourg => "Luxembourg"
  | Malawi => "Malawi"
  | Malaysia => "Malaysia"
  | Mali => "Mali"
  | Mauritania => "Mauritania"
  | Mexico => "Mexico"
  | Moldova => "Moldova"
  | Mongolia => "Mongolia"
  | Montenegro => "Montenegro"
  | Morocco => "Morocco"
  | Mozambique => "Mozambique"
  | Myanmar => "Myanmar"
  | Namibia => "Namibia"
  | Nepal => "Nepal"
  | Netherlands => "Netherlands"
  | Nicaragua => "Nicaragua"
  | Niger => "Niger"
  | Nigeria => "Nigeria"
  | North_Korea => "North Korea"
  | North_Macedonia => "North Macedonia"
  | Norway => "Norway"
  | Pakistan => "Pakistan"
  | Palestine => "Palestine"
  | Panama => "Panama"
  | Paraguay => "Paraguay"
  | Peru => "Peru"
  | Philippines => "Philippines"
  | Poland => "Poland"
  | Portugal => "Portugal"
  | Republic_of_the_Congo => "Republic of the Congo"
  | Romania => "Romania"
  | Russia => "Russia"
  | Rwanda => "Rwanda"
  | Senegal => "Senegal"
  | Serbia => "Serbia"
  | Sierra_Leone => "Sierra Leone"
  | Singapore => "Singapore"
  | Slovakia => "Slovakia"
  | Slovenia => "Slovenia"
  | Somalia => "Somalia"
  | South_Africa => "South Africa"
  | South_Korea => "South Korea"
  | South_Sudan => "South Sudan"
  | Spain => "Spain"
  | Sri_Lanka => "Sri Lanka"
  | Sudan => "Sudan"
  | Suriname => "Suriname"
  | Sweden => "Sweden"
  | Switzerland => "Switzerland"
  | Syria => "Syria"
  | Taiwan => "Taiwan"
  | Tajikistan => "Tajikistan"
  | Tanzania => "Tanzania"
  | Thailand => "Thailand"
  | Togo => "Togo"
  | Trinidad_and_Tobago => "Trinidad and Tobago"
  | Turkey => "Turkey"
  | Turkmenistan => "Turkmenistan"
  | Uganda => "Uganda"
  | Ukraine => "Ukraine"
  | United_Kingdom => "United Kingdom"
  | United_States => "United States"
  | Uzbekistan => "Uzbekistan"
  | Venezuela => "Venezuela"
  | Vietnam => "Vietnam"
  | Zambia => "Zambia"
  | Zimbabwe => "Zimbabwe"
  end.
(* IUCN Red List categories (MDD v2.5 iucnStatus). *)
Inductive IUCN : Type :=
| LC
| NT
| VU
| EN
| CR
| EW
| EX
| DD
| NE.

Definition iucn_index (x : IUCN) : nat :=
  match x with
  | LC => 0
  | NT => 1
  | VU => 2
  | EN => 3
  | CR => 4
  | EW => 5
  | EX => 6
  | DD => 7
  | NE => 8
  end.

Definition iucn_table : list IUCN := [
  LC; NT; VU; EN; CR; EW;
  EX; DD; NE].

Lemma iucn_table_index : forall x, nth_error iucn_table (iucn_index x) = Some x.
Proof. solve_table_index. Qed.

Lemma iucn_indices : map iucn_index iucn_table = seq 0 (List.length iucn_table).
Proof. vm_compute. reflexivity. Qed.

#[export] Instance Beq_IUCN : Beq IUCN :=
  {| beq := table_beq IUCN iucn_index;
     beq_spec := table_beq_spec IUCN iucn_index iucn_table iucn_table_index |}.

#[export] Instance Finite_IUCN : Finite IUCN :=
  {| enum := iucn_table;
     enum_complete := table_complete IUCN iucn_index iucn_table iucn_table_index;
     enum_nodup := table_nodup IUCN iucn_index iucn_table iucn_indices |}.

Definition iucn_name (x : IUCN) : string :=
  match x with
  | LC => "Least Concern"
  | NT => "Near Threatened"
  | VU => "Vulnerable"
  | EN => "Endangered"
  | CR => "Critically Endangered"
  | EW => "Extinct in the Wild"
  | EX => "Extinct"
  | DD => "Data Deficient"
  | NE => "Not Evaluated"
  end.
