(******************************************************************************)
(*  GENERATED by tools/gen_coq.py -- do not edit by hand.                     *)
(*  Source: data/mdd/MDD_v2.5_Sciuridae.csv (MDD v2.5, 2026-07-28; CC-BY 4.0)   *)
(******************************************************************************)

From Coq Require Import List String.
From Sciuridae Require Import Lib.Base.
Import ListNotations.
Local Open Scope string_scope.

(* Subfamilies of Sciuridae (MDD v2.5). *)
Inductive Subfamily : Type :=
| Ratufinae
| Sciurillinae
| Sciurinae
| Nannosciurinae
| Xerinae.

Definition subfamily_index (x : Subfamily) : nat :=
  match x with
  | Ratufinae => 0
  | Sciurillinae => 1
  | Sciurinae => 2
  | Nannosciurinae => 3
  | Xerinae => 4
  end.

Definition subfamily_table : list Subfamily := [
  Ratufinae; Sciurillinae; Sciurinae; Nannosciurinae; Xerinae].

Lemma subfamily_table_index : forall x, nth_error subfamily_table (subfamily_index x) = Some x.
Proof. solve_table_index. Qed.

Lemma subfamily_indices : map subfamily_index subfamily_table = seq 0 (List.length subfamily_table).
Proof. vm_compute. reflexivity. Qed.

#[export] Instance Beq_Subfamily : Beq Subfamily :=
  {| beq := table_beq Subfamily subfamily_index;
     beq_spec := table_beq_spec Subfamily subfamily_index subfamily_table subfamily_table_index |}.

#[export] Instance Finite_Subfamily : Finite Subfamily :=
  {| enum := subfamily_table;
     enum_complete := table_complete Subfamily subfamily_index subfamily_table subfamily_table_index;
     enum_nodup := table_nodup Subfamily subfamily_index subfamily_table subfamily_indices |}.

Definition subfamily_name (x : Subfamily) : string :=
  match x with
  | Ratufinae => "Ratufinae"
  | Sciurillinae => "Sciurillinae"
  | Sciurinae => "Sciurinae"
  | Nannosciurinae => "Nannosciurinae"
  | Xerinae => "Xerinae"
  end.
(* Tribes of Sciuridae (MDD v2.5). *)
Inductive Tribe : Type :=
| Exilisciurini
| Funambulini
| Nannosciurini
| Pteromyini
| Sciurini
| Marmotini
| Protoxerini
| Sciurotamiini
| Tamiini
| Xerini.

Definition tribe_index (x : Tribe) : nat :=
  match x with
  | Exilisciurini => 0
  | Funambulini => 1
  | Nannosciurini => 2
  | Pteromyini => 3
  | Sciurini => 4
  | Marmotini => 5
  | Protoxerini => 6
  | Sciurotamiini => 7
  | Tamiini => 8
  | Xerini => 9
  end.

Definition tribe_table : list Tribe := [
  Exilisciurini; Funambulini; Nannosciurini; Pteromyini; Sciurini; Marmotini;
  Protoxerini; Sciurotamiini; Tamiini; Xerini].

Lemma tribe_table_index : forall x, nth_error tribe_table (tribe_index x) = Some x.
Proof. solve_table_index. Qed.

Lemma tribe_indices : map tribe_index tribe_table = seq 0 (List.length tribe_table).
Proof. vm_compute. reflexivity. Qed.

#[export] Instance Beq_Tribe : Beq Tribe :=
  {| beq := table_beq Tribe tribe_index;
     beq_spec := table_beq_spec Tribe tribe_index tribe_table tribe_table_index |}.

#[export] Instance Finite_Tribe : Finite Tribe :=
  {| enum := tribe_table;
     enum_complete := table_complete Tribe tribe_index tribe_table tribe_table_index;
     enum_nodup := table_nodup Tribe tribe_index tribe_table tribe_indices |}.

Definition tribe_name (x : Tribe) : string :=
  match x with
  | Exilisciurini => "Exilisciurini"
  | Funambulini => "Funambulini"
  | Nannosciurini => "Nannosciurini"
  | Pteromyini => "Pteromyini"
  | Sciurini => "Sciurini"
  | Marmotini => "Marmotini"
  | Protoxerini => "Protoxerini"
  | Sciurotamiini => "Sciurotamiini"
  | Tamiini => "Tamiini"
  | Xerini => "Xerini"
  end.
(* The 64 genera of Sciuridae recognised by MDD v2.5, in MDD order. *)
Inductive Genus : Type :=
| Exilisciurus
| Funambulus
| Hyosciurus
| Prosciurillus
| Rubrisciurus
| Callosciurus
| Dremomys
| Glyphotes
| Lariscus
| Menetes
| Nannosciurus
| Rhinosciurus
| Sundasciurus
| Tamiops
| Ratufa
| Sciurillus
| Eoglaucomys
| Glaucomys
| Hylopetes
| Iomys
| Olisthomys
| Petaurillus
| Petinomys
| Priapomys
| Aeretes
| Aeromys
| Belomys
| Biswamoyopterus
| Eupetaurus
| Petaurista
| Pteromys
| Pteromyscus
| Trogopterus
| Microsciurus
| Rheithrosciurus
| Sciurus
| Syntheosciurus
| Tamiasciurus
| Ammospermophilus
| Notocitellus
| Marmota
| Callospermophilus
| Otospermophilus
| Cynomys
| Ictidomys
| Poliocitellus
| Spermophilus
| Urocitellus
| Xerospermophilus
| Epixerus
| Funisciurus
| Heliosciurus
| Myosciurus
| Paraxerus
| Protoxerus
| Sciurotamias
| Eutamias
| Neotamias
| Tamias
| Spermophilopsis
| Atlantoxerus
| Euxerus
| Geosciurus
| Xerus.

Definition genus_index (x : Genus) : nat :=
  match x with
  | Exilisciurus => 0
  | Funambulus => 1
  | Hyosciurus => 2
  | Prosciurillus => 3
  | Rubrisciurus => 4
  | Callosciurus => 5
  | Dremomys => 6
  | Glyphotes => 7
  | Lariscus => 8
  | Menetes => 9
  | Nannosciurus => 10
  | Rhinosciurus => 11
  | Sundasciurus => 12
  | Tamiops => 13
  | Ratufa => 14
  | Sciurillus => 15
  | Eoglaucomys => 16
  | Glaucomys => 17
  | Hylopetes => 18
  | Iomys => 19
  | Olisthomys => 20
  | Petaurillus => 21
  | Petinomys => 22
  | Priapomys => 23
  | Aeretes => 24
  | Aeromys => 25
  | Belomys => 26
  | Biswamoyopterus => 27
  | Eupetaurus => 28
  | Petaurista => 29
  | Pteromys => 30
  | Pteromyscus => 31
  | Trogopterus => 32
  | Microsciurus => 33
  | Rheithrosciurus => 34
  | Sciurus => 35
  | Syntheosciurus => 36
  | Tamiasciurus => 37
  | Ammospermophilus => 38
  | Notocitellus => 39
  | Marmota => 40
  | Callospermophilus => 41
  | Otospermophilus => 42
  | Cynomys => 43
  | Ictidomys => 44
  | Poliocitellus => 45
  | Spermophilus => 46
  | Urocitellus => 47
  | Xerospermophilus => 48
  | Epixerus => 49
  | Funisciurus => 50
  | Heliosciurus => 51
  | Myosciurus => 52
  | Paraxerus => 53
  | Protoxerus => 54
  | Sciurotamias => 55
  | Eutamias => 56
  | Neotamias => 57
  | Tamias => 58
  | Spermophilopsis => 59
  | Atlantoxerus => 60
  | Euxerus => 61
  | Geosciurus => 62
  | Xerus => 63
  end.

Definition genus_table : list Genus := [
  Exilisciurus; Funambulus; Hyosciurus; Prosciurillus; Rubrisciurus; Callosciurus;
  Dremomys; Glyphotes; Lariscus; Menetes; Nannosciurus; Rhinosciurus;
  Sundasciurus; Tamiops; Ratufa; Sciurillus; Eoglaucomys; Glaucomys;
  Hylopetes; Iomys; Olisthomys; Petaurillus; Petinomys; Priapomys;
  Aeretes; Aeromys; Belomys; Biswamoyopterus; Eupetaurus; Petaurista;
  Pteromys; Pteromyscus; Trogopterus; Microsciurus; Rheithrosciurus; Sciurus;
  Syntheosciurus; Tamiasciurus; Ammospermophilus; Notocitellus; Marmota; Callospermophilus;
  Otospermophilus; Cynomys; Ictidomys; Poliocitellus; Spermophilus; Urocitellus;
  Xerospermophilus; Epixerus; Funisciurus; Heliosciurus; Myosciurus; Paraxerus;
  Protoxerus; Sciurotamias; Eutamias; Neotamias; Tamias; Spermophilopsis;
  Atlantoxerus; Euxerus; Geosciurus; Xerus].

Lemma genus_table_index : forall x, nth_error genus_table (genus_index x) = Some x.
Proof. solve_table_index. Qed.

Lemma genus_indices : map genus_index genus_table = seq 0 (List.length genus_table).
Proof. vm_compute. reflexivity. Qed.

#[export] Instance Beq_Genus : Beq Genus :=
  {| beq := table_beq Genus genus_index;
     beq_spec := table_beq_spec Genus genus_index genus_table genus_table_index |}.

#[export] Instance Finite_Genus : Finite Genus :=
  {| enum := genus_table;
     enum_complete := table_complete Genus genus_index genus_table genus_table_index;
     enum_nodup := table_nodup Genus genus_index genus_table genus_indices |}.

Definition genus_name (x : Genus) : string :=
  match x with
  | Exilisciurus => "Exilisciurus"
  | Funambulus => "Funambulus"
  | Hyosciurus => "Hyosciurus"
  | Prosciurillus => "Prosciurillus"
  | Rubrisciurus => "Rubrisciurus"
  | Callosciurus => "Callosciurus"
  | Dremomys => "Dremomys"
  | Glyphotes => "Glyphotes"
  | Lariscus => "Lariscus"
  | Menetes => "Menetes"
  | Nannosciurus => "Nannosciurus"
  | Rhinosciurus => "Rhinosciurus"
  | Sundasciurus => "Sundasciurus"
  | Tamiops => "Tamiops"
  | Ratufa => "Ratufa"
  | Sciurillus => "Sciurillus"
  | Eoglaucomys => "Eoglaucomys"
  | Glaucomys => "Glaucomys"
  | Hylopetes => "Hylopetes"
  | Iomys => "Iomys"
  | Olisthomys => "Olisthomys"
  | Petaurillus => "Petaurillus"
  | Petinomys => "Petinomys"
  | Priapomys => "Priapomys"
  | Aeretes => "Aeretes"
  | Aeromys => "Aeromys"
  | Belomys => "Belomys"
  | Biswamoyopterus => "Biswamoyopterus"
  | Eupetaurus => "Eupetaurus"
  | Petaurista => "Petaurista"
  | Pteromys => "Pteromys"
  | Pteromyscus => "Pteromyscus"
  | Trogopterus => "Trogopterus"
  | Microsciurus => "Microsciurus"
  | Rheithrosciurus => "Rheithrosciurus"
  | Sciurus => "Sciurus"
  | Syntheosciurus => "Syntheosciurus"
  | Tamiasciurus => "Tamiasciurus"
  | Ammospermophilus => "Ammospermophilus"
  | Notocitellus => "Notocitellus"
  | Marmota => "Marmota"
  | Callospermophilus => "Callospermophilus"
  | Otospermophilus => "Otospermophilus"
  | Cynomys => "Cynomys"
  | Ictidomys => "Ictidomys"
  | Poliocitellus => "Poliocitellus"
  | Spermophilus => "Spermophilus"
  | Urocitellus => "Urocitellus"
  | Xerospermophilus => "Xerospermophilus"
  | Epixerus => "Epixerus"
  | Funisciurus => "Funisciurus"
  | Heliosciurus => "Heliosciurus"
  | Myosciurus => "Myosciurus"
  | Paraxerus => "Paraxerus"
  | Protoxerus => "Protoxerus"
  | Sciurotamias => "Sciurotamias"
  | Eutamias => "Eutamias"
  | Neotamias => "Neotamias"
  | Tamias => "Tamias"
  | Spermophilopsis => "Spermophilopsis"
  | Atlantoxerus => "Atlantoxerus"
  | Euxerus => "Euxerus"
  | Geosciurus => "Geosciurus"
  | Xerus => "Xerus"
  end.
(* The subfamily containing each tribe. *)
Definition tribe_subfamily (t : Tribe) : Subfamily :=
  match t with
  | Exilisciurini => Nannosciurinae
  | Funambulini => Nannosciurinae
  | Nannosciurini => Nannosciurinae
  | Pteromyini => Sciurinae
  | Sciurini => Sciurinae
  | Marmotini => Xerinae
  | Protoxerini => Xerinae
  | Sciurotamiini => Xerinae
  | Tamiini => Xerinae
  | Xerini => Xerinae
  end.

(* Where a genus sits: in a tribe, or directly in a subfamily that has no
   tribes.  Subfamily membership is derived from this, so the ranks nest
   by construction. *)
Inductive Placement : Type :=
| InTribe : Tribe -> Placement
| InSubfamily : Subfamily -> Placement.

Definition genus_placement (g : Genus) : Placement :=
  match g with
  | Exilisciurus => InTribe Exilisciurini
  | Funambulus => InTribe Funambulini
  | Hyosciurus => InTribe Nannosciurini
  | Prosciurillus => InTribe Nannosciurini
  | Rubrisciurus => InTribe Nannosciurini
  | Callosciurus => InTribe Nannosciurini
  | Dremomys => InTribe Nannosciurini
  | Glyphotes => InTribe Nannosciurini
  | Lariscus => InTribe Nannosciurini
  | Menetes => InTribe Nannosciurini
  | Nannosciurus => InTribe Nannosciurini
  | Rhinosciurus => InTribe Nannosciurini
  | Sundasciurus => InTribe Nannosciurini
  | Tamiops => InTribe Nannosciurini
  | Ratufa => InSubfamily Ratufinae
  | Sciurillus => InSubfamily Sciurillinae
  | Eoglaucomys => InTribe Pteromyini
  | Glaucomys => InTribe Pteromyini
  | Hylopetes => InTribe Pteromyini
  | Iomys => InTribe Pteromyini
  | Olisthomys => InTribe Pteromyini
  | Petaurillus => InTribe Pteromyini
  | Petinomys => InTribe Pteromyini
  | Priapomys => InTribe Pteromyini
  | Aeretes => InTribe Pteromyini
  | Aeromys => InTribe Pteromyini
  | Belomys => InTribe Pteromyini
  | Biswamoyopterus => InTribe Pteromyini
  | Eupetaurus => InTribe Pteromyini
  | Petaurista => InTribe Pteromyini
  | Pteromys => InTribe Pteromyini
  | Pteromyscus => InTribe Pteromyini
  | Trogopterus => InTribe Pteromyini
  | Microsciurus => InTribe Sciurini
  | Rheithrosciurus => InTribe Sciurini
  | Sciurus => InTribe Sciurini
  | Syntheosciurus => InTribe Sciurini
  | Tamiasciurus => InTribe Sciurini
  | Ammospermophilus => InTribe Marmotini
  | Notocitellus => InTribe Marmotini
  | Marmota => InTribe Marmotini
  | Callospermophilus => InTribe Marmotini
  | Otospermophilus => InTribe Marmotini
  | Cynomys => InTribe Marmotini
  | Ictidomys => InTribe Marmotini
  | Poliocitellus => InTribe Marmotini
  | Spermophilus => InTribe Marmotini
  | Urocitellus => InTribe Marmotini
  | Xerospermophilus => InTribe Marmotini
  | Epixerus => InTribe Protoxerini
  | Funisciurus => InTribe Protoxerini
  | Heliosciurus => InTribe Protoxerini
  | Myosciurus => InTribe Protoxerini
  | Paraxerus => InTribe Protoxerini
  | Protoxerus => InTribe Protoxerini
  | Sciurotamias => InTribe Sciurotamiini
  | Eutamias => InTribe Tamiini
  | Neotamias => InTribe Tamiini
  | Tamias => InTribe Tamiini
  | Spermophilopsis => InTribe Xerini
  | Atlantoxerus => InTribe Xerini
  | Euxerus => InTribe Xerini
  | Geosciurus => InTribe Xerini
  | Xerus => InTribe Xerini
  end.

