(******************************************************************************)
(*  GENERATED by tools/gen_coq.py -- do not edit by hand.                     *)
(*  Source: data/upham2019/Sciuridae_DNAonly_MCC.nwk (Upham et al. 2019, PLoS Biol.)*)
(******************************************************************************)
(*  Sciurid subtree of the DNA-only, topology-free, node-dated maximum clade  *)
(*  credibility tree of Upham, Esselstyn and Jetz (2019), Inferring the       *)
(*  mammal tree, PLoS Biology 17(12): e3000494.  Internal nodes carry the     *)
(*  posterior probability (per mille, rounded down), the node height and its *)
(*  95% HPD interval (widened outward), all in units of 0.01 Ma.  Tips are    *)
(*  numbered (as N) left to right; each is mapped to the MDD v2.5 species it  *)
(*  now belongs to (data/upham2019/tip_map.csv).                              *)
(******************************************************************************)

From Coq Require Import List String NArith.
From Sciuridae Require Import Lib.Base Phylo.Tree Data.Taxonomy Data.Species.
Import ListNotations.
Local Open Scope string_scope.

Record TipInfo : Type := { tip_label : string; tip_species : AnySpecies }.

Definition tips : list TipInfo := [
  {| tip_label := "Ratufa_bicolor_SCIURIDAE_RODENTIA"; tip_species := sp Ratufa_bicolor |};
  {| tip_label := "Ratufa_affinis_SCIURIDAE_RODENTIA"; tip_species := sp Ratufa_affinis |};
  {| tip_label := "Ratufa_macroura_SCIURIDAE_RODENTIA"; tip_species := sp Ratufa_macroura |};
  {| tip_label := "Sciurillus_pusillus_SCIURIDAE_RODENTIA"; tip_species := sp Sciurillus_pusillus |};
  {| tip_label := "Protoxerus_stangeri_SCIURIDAE_RODENTIA"; tip_species := sp Protoxerus_stangeri |};
  {| tip_label := "Epixerus_ebii_SCIURIDAE_RODENTIA"; tip_species := sp Epixerus_ebii |};
  {| tip_label := "Funisciurus_carruthersi_SCIURIDAE_RODENTIA"; tip_species := sp Funisciurus_carruthersi |};
  {| tip_label := "Funisciurus_pyrropus_SCIURIDAE_RODENTIA"; tip_species := sp Funisciurus_pyrropus |};
  {| tip_label := "Paraxerus_ochraceus_SCIURIDAE_RODENTIA"; tip_species := sp Paraxerus_ochraceus |};
  {| tip_label := "Paraxerus_cepapi_SCIURIDAE_RODENTIA"; tip_species := sp Paraxerus_cepapi |};
  {| tip_label := "Paraxerus_vexillarius_SCIURIDAE_RODENTIA"; tip_species := sp Paraxerus_vexillarius |};
  {| tip_label := "Paraxerus_alexandri_SCIURIDAE_RODENTIA"; tip_species := sp Paraxerus_alexandri |};
  {| tip_label := "Heliosciurus_undulatus_SCIURIDAE_RODENTIA"; tip_species := sp Heliosciurus_undulatus |};
  {| tip_label := "Heliosciurus_ruwenzorii_SCIURIDAE_RODENTIA"; tip_species := sp Heliosciurus_ruwenzorii |};
  {| tip_label := "Myosciurus_pumilio_SCIURIDAE_RODENTIA"; tip_species := sp Myosciurus_pumilio |};
  {| tip_label := "Tamias_alpinus_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_alpinus |};
  {| tip_label := "Tamias_panamintinus_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_panamintinus |};
  {| tip_label := "Tamias_minimus_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_minimus |};
  {| tip_label := "Tamias_speciosus_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_speciosus |};
  {| tip_label := "Tamias_quadrimaculatus_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_quadrimaculatus |};
  {| tip_label := "Tamias_ruficaudus_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_ruficaudus |};
  {| tip_label := "Tamias_rufus_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_rufus |};
  {| tip_label := "Tamias_umbrinus_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_umbrinus |};
  {| tip_label := "Tamias_quadrivittatus_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_quadrivittatus |};
  {| tip_label := "Tamias_cinereicollis_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_cinereicollis |};
  {| tip_label := "Tamias_dorsalis_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_dorsalis |};
  {| tip_label := "Tamias_palmeri_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_palmeri |};
  {| tip_label := "Tamias_bulleri_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_bulleri |};
  {| tip_label := "Tamias_canipes_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_canipes |};
  {| tip_label := "Tamias_durangae_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_durangae |};
  {| tip_label := "Tamias_merriami_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_merriami |};
  {| tip_label := "Tamias_obscurus_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_obscurus |};
  {| tip_label := "Tamias_siskiyou_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_siskiyou |};
  {| tip_label := "Tamias_senex_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_senex |};
  {| tip_label := "Tamias_sonomae_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_sonomae |};
  {| tip_label := "Tamias_townsendii_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_townsendii |};
  {| tip_label := "Tamias_ochrogenys_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_ochrogenys |};
  {| tip_label := "Tamias_amoenus_SCIURIDAE_RODENTIA"; tip_species := sp Neotamias_amoenus |};
  {| tip_label := "Tamias_striatus_SCIURIDAE_RODENTIA"; tip_species := sp Tamias_striatus |};
  {| tip_label := "Tamias_sibiricus_SCIURIDAE_RODENTIA"; tip_species := sp Eutamias_sibiricus |};
  {| tip_label := "Marmota_marmota_SCIURIDAE_RODENTIA"; tip_species := sp Marmota_marmota |};
  {| tip_label := "Marmota_caudata_SCIURIDAE_RODENTIA"; tip_species := sp Marmota_caudata |};
  {| tip_label := "Marmota_menzbieri_SCIURIDAE_RODENTIA"; tip_species := sp Marmota_menzbieri |};
  {| tip_label := "Marmota_broweri_SCIURIDAE_RODENTIA"; tip_species := sp Marmota_broweri |};
  {| tip_label := "Marmota_sibirica_SCIURIDAE_RODENTIA"; tip_species := sp Marmota_sibirica |};
  {| tip_label := "Marmota_camtschatica_SCIURIDAE_RODENTIA"; tip_species := sp Marmota_camtschatica |};
  {| tip_label := "Marmota_himalayana_SCIURIDAE_RODENTIA"; tip_species := sp Marmota_himalayana |};
  {| tip_label := "Marmota_baibacina_SCIURIDAE_RODENTIA"; tip_species := sp Marmota_baibacina |};
  {| tip_label := "Marmota_monax_SCIURIDAE_RODENTIA"; tip_species := sp Marmota_monax |};
  {| tip_label := "Marmota_bobak_SCIURIDAE_RODENTIA"; tip_species := sp Marmota_bobak |};
  {| tip_label := "Marmota_olympus_SCIURIDAE_RODENTIA"; tip_species := sp Marmota_olympus |};
  {| tip_label := "Marmota_caligata_SCIURIDAE_RODENTIA"; tip_species := sp Marmota_caligata |};
  {| tip_label := "Marmota_vancouverensis_SCIURIDAE_RODENTIA"; tip_species := sp Marmota_vancouverensis |};
  {| tip_label := "Marmota_flaviventris_SCIURIDAE_RODENTIA"; tip_species := sp Marmota_flaviventris |};
  {| tip_label := "Spermophilus_pygmaeus_SCIURIDAE_RODENTIA"; tip_species := sp Spermophilus_pygmaeus |};
  {| tip_label := "Spermophilus_dauricus_SCIURIDAE_RODENTIA"; tip_species := sp Spermophilus_dauricus |};
  {| tip_label := "Spermophilus_relictus_SCIURIDAE_RODENTIA"; tip_species := sp Spermophilus_relictus |};
  {| tip_label := "Spermophilus_erythrogenys_SCIURIDAE_RODENTIA"; tip_species := sp Spermophilus_erythrogenys |};
  {| tip_label := "Spermophilus_major_SCIURIDAE_RODENTIA"; tip_species := sp Spermophilus_major |};
  {| tip_label := "Spermophilus_fulvus_SCIURIDAE_RODENTIA"; tip_species := sp Spermophilus_fulvus |};
  {| tip_label := "Spermophilus_alashanicus_SCIURIDAE_RODENTIA"; tip_species := sp Spermophilus_alaschanicus |};
  {| tip_label := "Spermophilus_pallidicauda_SCIURIDAE_RODENTIA"; tip_species := sp Spermophilus_pallidicauda |};
  {| tip_label := "Spermophilus_suslicus_SCIURIDAE_RODENTIA"; tip_species := sp Spermophilus_suslicus |};
  {| tip_label := "Spermophilus_xanthoprymnus_SCIURIDAE_RODENTIA"; tip_species := sp Spermophilus_xanthoprymnus |};
  {| tip_label := "Spermophilus_taurensis_SCIURIDAE_RODENTIA"; tip_species := sp Spermophilus_taurensis |};
  {| tip_label := "Spermophilus_citellus_SCIURIDAE_RODENTIA"; tip_species := sp Spermophilus_citellus |};
  {| tip_label := "Xerospermophilus_perotensis_SCIURIDAE_RODENTIA"; tip_species := sp Xerospermophilus_perotensis |};
  {| tip_label := "Xerospermophilus_spilosoma_SCIURIDAE_RODENTIA"; tip_species := sp Xerospermophilus_spilosoma |};
  {| tip_label := "Xerospermophilus_mohavensis_SCIURIDAE_RODENTIA"; tip_species := sp Xerospermophilus_mohavensis |};
  {| tip_label := "Xerospermophilus_tereticaudus_SCIURIDAE_RODENTIA"; tip_species := sp Xerospermophilus_tereticaudus |};
  {| tip_label := "Cynomys_parvidens_SCIURIDAE_RODENTIA"; tip_species := sp Cynomys_parvidens |};
  {| tip_label := "Cynomys_gunnisoni_SCIURIDAE_RODENTIA"; tip_species := sp Cynomys_gunnisoni |};
  {| tip_label := "Cynomys_leucurus_SCIURIDAE_RODENTIA"; tip_species := sp Cynomys_leucurus |};
  {| tip_label := "Cynomys_ludovicianus_SCIURIDAE_RODENTIA"; tip_species := sp Cynomys_ludovicianus |};
  {| tip_label := "Cynomys_mexicanus_SCIURIDAE_RODENTIA"; tip_species := sp Cynomys_mexicanus |};
  {| tip_label := "Poliocitellus_franklinii_SCIURIDAE_RODENTIA"; tip_species := sp Poliocitellus_franklinii |};
  {| tip_label := "Ictidomys_tridecemlineatus_SCIURIDAE_RODENTIA"; tip_species := sp Ictidomys_tridecemlineatus |};
  {| tip_label := "Ictidomys_parvidens_SCIURIDAE_RODENTIA"; tip_species := sp Ictidomys_parvidens |};
  {| tip_label := "Ictidomys_mexicanus_SCIURIDAE_RODENTIA"; tip_species := sp Ictidomys_mexicanus |};
  {| tip_label := "Urocitellus_beldingi_SCIURIDAE_RODENTIA"; tip_species := sp Urocitellus_beldingi |};
  {| tip_label := "Urocitellus_armatus_SCIURIDAE_RODENTIA"; tip_species := sp Urocitellus_armatus |};
  {| tip_label := "Urocitellus_townsendii_SCIURIDAE_RODENTIA"; tip_species := sp Urocitellus_townsendii |};
  {| tip_label := "Urocitellus_washingtoni_SCIURIDAE_RODENTIA"; tip_species := sp Urocitellus_washingtoni |};
  {| tip_label := "Urocitellus_canus_SCIURIDAE_RODENTIA"; tip_species := sp Urocitellus_canus |};
  {| tip_label := "Urocitellus_mollis_SCIURIDAE_RODENTIA"; tip_species := sp Urocitellus_mollis |};
  {| tip_label := "Urocitellus_brunneus_SCIURIDAE_RODENTIA"; tip_species := sp Urocitellus_brunneus |};
  {| tip_label := "Urocitellus_columbianus_SCIURIDAE_RODENTIA"; tip_species := sp Urocitellus_columbianus |};
  {| tip_label := "Urocitellus_elegans_SCIURIDAE_RODENTIA"; tip_species := sp Urocitellus_elegans |};
  {| tip_label := "Urocitellus_richardsonii_SCIURIDAE_RODENTIA"; tip_species := sp Urocitellus_richardsonii |};
  {| tip_label := "Urocitellus_parryii_SCIURIDAE_RODENTIA"; tip_species := sp Urocitellus_parryii |};
  {| tip_label := "Urocitellus_undulatus_SCIURIDAE_RODENTIA"; tip_species := sp Urocitellus_undulatus |};
  {| tip_label := "Otospermophilus_atricapillus_SCIURIDAE_RODENTIA"; tip_species := sp Otospermophilus_beecheyi |};
  {| tip_label := "Otospermophilus_beecheyi_SCIURIDAE_RODENTIA"; tip_species := sp Otospermophilus_beecheyi |};
  {| tip_label := "Otospermophilus_variegatus_SCIURIDAE_RODENTIA"; tip_species := sp Otospermophilus_variegatus |};
  {| tip_label := "Callospermophilus_lateralis_SCIURIDAE_RODENTIA"; tip_species := sp Callospermophilus_lateralis |};
  {| tip_label := "Callospermophilus_madrensis_SCIURIDAE_RODENTIA"; tip_species := sp Callospermophilus_madrensis |};
  {| tip_label := "Callospermophilus_saturatus_SCIURIDAE_RODENTIA"; tip_species := sp Callospermophilus_saturatus |};
  {| tip_label := "Ammospermophilus_harrisii_SCIURIDAE_RODENTIA"; tip_species := sp Ammospermophilus_harrisii |};
  {| tip_label := "Ammospermophilus_leucurus_SCIURIDAE_RODENTIA"; tip_species := sp Ammospermophilus_leucurus |};
  {| tip_label := "Ammospermophilus_interpres_SCIURIDAE_RODENTIA"; tip_species := sp Ammospermophilus_interpres |};
  {| tip_label := "Notocitellus_annulatus_SCIURIDAE_RODENTIA"; tip_species := sp Notocitellus_annulatus |};
  {| tip_label := "Notocitellus_adocetus_SCIURIDAE_RODENTIA"; tip_species := sp Notocitellus_adocetus |};
  {| tip_label := "Sciurotamias_davidianus_SCIURIDAE_RODENTIA"; tip_species := sp Sciurotamias_davidianus |};
  {| tip_label := "Spermophilopsis_leptodactylus_SCIURIDAE_RODENTIA"; tip_species := sp Spermophilopsis_leptodactyla |};
  {| tip_label := "Atlantoxerus_getulus_SCIURIDAE_RODENTIA"; tip_species := sp Atlantoxerus_getulus |};
  {| tip_label := "Xerus_rutilus_SCIURIDAE_RODENTIA"; tip_species := sp Xerus_rutilus |};
  {| tip_label := "Xerus_inauris_SCIURIDAE_RODENTIA"; tip_species := sp Geosciurus_inauris |};
  {| tip_label := "Xerus_princeps_SCIURIDAE_RODENTIA"; tip_species := sp Geosciurus_princeps |};
  {| tip_label := "Xerus_erythropus_SCIURIDAE_RODENTIA"; tip_species := sp Euxerus_erythropus |};
  {| tip_label := "Dremomys_gularis_SCIURIDAE_RODENTIA"; tip_species := sp Dremomys_gularis |};
  {| tip_label := "Dremomys_pyrrhomerus_SCIURIDAE_RODENTIA"; tip_species := sp Dremomys_pyrrhomerus |};
  {| tip_label := "Dremomys_rufigenis_SCIURIDAE_RODENTIA"; tip_species := sp Dremomys_rufigenis |};
  {| tip_label := "Dremomys_lokriah_SCIURIDAE_RODENTIA"; tip_species := sp Dremomys_lokriah |};
  {| tip_label := "Dremomys_pernyi_SCIURIDAE_RODENTIA"; tip_species := sp Dremomys_pernyi |};
  {| tip_label := "Tamiops_macclellandii_SCIURIDAE_RODENTIA"; tip_species := sp Tamiops_mcclellandii |};
  {| tip_label := "Tamiops_maritimus_SCIURIDAE_RODENTIA"; tip_species := sp Tamiops_maritimus |};
  {| tip_label := "Tamiops_swinhoei_SCIURIDAE_RODENTIA"; tip_species := sp Tamiops_swinhoei |};
  {| tip_label := "Tamiops_rodolphii_SCIURIDAE_RODENTIA"; tip_species := sp Tamiops_rodolphii |};
  {| tip_label := "Callosciurus_nigrovittatus_SCIURIDAE_RODENTIA"; tip_species := sp Callosciurus_nigrovittatus |};
  {| tip_label := "Callosciurus_prevostii_SCIURIDAE_RODENTIA"; tip_species := sp Callosciurus_prevostii |};
  {| tip_label := "Callosciurus_caniceps_SCIURIDAE_RODENTIA"; tip_species := sp Callosciurus_caniceps |};
  {| tip_label := "Callosciurus_inornatus_SCIURIDAE_RODENTIA"; tip_species := sp Callosciurus_inornatus |};
  {| tip_label := "Callosciurus_finlaysonii_SCIURIDAE_RODENTIA"; tip_species := sp Callosciurus_finlaysonii |};
  {| tip_label := "Callosciurus_erythraeus_SCIURIDAE_RODENTIA"; tip_species := sp Callosciurus_erythraeus |};
  {| tip_label := "Callosciurus_notatus_SCIURIDAE_RODENTIA"; tip_species := sp Callosciurus_notatus |};
  {| tip_label := "Callosciurus_orestes_SCIURIDAE_RODENTIA"; tip_species := sp Callosciurus_orestes |};
  {| tip_label := "Sundasciurus_brookei_SCIURIDAE_RODENTIA"; tip_species := sp Sundasciurus_brookei |};
  {| tip_label := "Rubrisciurus_rubriventer_SCIURIDAE_RODENTIA"; tip_species := sp Rubrisciurus_rubriventer |};
  {| tip_label := "Prosciurillus_murinus_SCIURIDAE_RODENTIA"; tip_species := sp Prosciurillus_murinus |};
  {| tip_label := "Sundasciurus_tenuis_SCIURIDAE_RODENTIA"; tip_species := sp Sundasciurus_tenuis |};
  {| tip_label := "Sundasciurus_jentinki_SCIURIDAE_RODENTIA"; tip_species := sp Sundasciurus_jentinki |};
  {| tip_label := "Hyosciurus_heinrichi_SCIURIDAE_RODENTIA"; tip_species := sp Hyosciurus_heinrichi |};
  {| tip_label := "Sundasciurus_rabori_SCIURIDAE_RODENTIA"; tip_species := sp Sundasciurus_rabori |};
  {| tip_label := "Nannosciurus_melanotis_SCIURIDAE_RODENTIA"; tip_species := sp Nannosciurus_melanotis |};
  {| tip_label := "Sundasciurus_steerii_SCIURIDAE_RODENTIA"; tip_species := sp Sundasciurus_steerii |};
  {| tip_label := "Sundasciurus_hoogstraali_SCIURIDAE_RODENTIA"; tip_species := sp Sundasciurus_hoogstraali |};
  {| tip_label := "Sundasciurus_juvencus_SCIURIDAE_RODENTIA"; tip_species := sp Sundasciurus_juvencus |};
  {| tip_label := "Sundasciurus_moellendorffi_SCIURIDAE_RODENTIA"; tip_species := sp Sundasciurus_moellendorffi |};
  {| tip_label := "Sundasciurus_mindanensis_SCIURIDAE_RODENTIA"; tip_species := sp Sundasciurus_mindanensis |};
  {| tip_label := "Sundasciurus_philippinensis_SCIURIDAE_RODENTIA"; tip_species := sp Sundasciurus_philippinensis |};
  {| tip_label := "Sundasciurus_samarensis_SCIURIDAE_RODENTIA"; tip_species := sp Sundasciurus_samarensis |};
  {| tip_label := "Sundasciurus_hippurus_SCIURIDAE_RODENTIA"; tip_species := sp Sundasciurus_hippurus |};
  {| tip_label := "Menetes_berdmorei_SCIURIDAE_RODENTIA"; tip_species := sp Menetes_berdmorei |};
  {| tip_label := "Sundasciurus_fraterculus_SCIURIDAE_RODENTIA"; tip_species := sp Sundasciurus_fraterculus |};
  {| tip_label := "Sundasciurus_lowii_SCIURIDAE_RODENTIA"; tip_species := sp Sundasciurus_lowii |};
  {| tip_label := "Rhinosciurus_laticaudatus_SCIURIDAE_RODENTIA"; tip_species := sp Rhinosciurus_laticaudatus |};
  {| tip_label := "Lariscus_insignis_SCIURIDAE_RODENTIA"; tip_species := sp Lariscus_insignis |};
  {| tip_label := "Exilisciurus_exilis_SCIURIDAE_RODENTIA"; tip_species := sp Exilisciurus_exilis |};
  {| tip_label := "Exilisciurus_concinnus_SCIURIDAE_RODENTIA"; tip_species := sp Exilisciurus_concinnus |};
  {| tip_label := "Funambulus_palmarum_SCIURIDAE_RODENTIA"; tip_species := sp Funambulus_palmarum |};
  {| tip_label := "Funambulus_pennantii_SCIURIDAE_RODENTIA"; tip_species := sp Funambulus_pennantii |};
  {| tip_label := "Sciurus_anomalus_SCIURIDAE_RODENTIA"; tip_species := sp Sciurus_anomalus |};
  {| tip_label := "Sciurus_griseus_SCIURIDAE_RODENTIA"; tip_species := sp Sciurus_griseus |};
  {| tip_label := "Sciurus_aberti_SCIURIDAE_RODENTIA"; tip_species := sp Sciurus_aberti |};
  {| tip_label := "Sciurus_carolinensis_SCIURIDAE_RODENTIA"; tip_species := sp Sciurus_carolinensis |};
  {| tip_label := "Sciurus_niger_SCIURIDAE_RODENTIA"; tip_species := sp Sciurus_niger |};
  {| tip_label := "Sciurus_deppei_SCIURIDAE_RODENTIA"; tip_species := sp Sciurus_deppei |};
  {| tip_label := "Sciurus_granatensis_SCIURIDAE_RODENTIA"; tip_species := sp Sciurus_granatensis |};
  {| tip_label := "Microsciurus_alfari_SCIURIDAE_RODENTIA"; tip_species := sp Microsciurus_alfari |};
  {| tip_label := "Sciurus_variegatoides_SCIURIDAE_RODENTIA"; tip_species := sp Sciurus_variegatoides |};
  {| tip_label := "Sciurus_oculatus_SCIURIDAE_RODENTIA"; tip_species := sp Sciurus_oculatus |};
  {| tip_label := "Sciurus_aureogaster_SCIURIDAE_RODENTIA"; tip_species := sp Sciurus_aureogaster |};
  {| tip_label := "Sciurus_gilvigularis_SCIURIDAE_RODENTIA"; tip_species := sp Sciurus_aestuans |};
  {| tip_label := "Sciurus_aestuans_SCIURIDAE_RODENTIA"; tip_species := sp Sciurus_aestuans |};
  {| tip_label := "Sciurus_spadiceus_SCIURIDAE_RODENTIA"; tip_species := sp Sciurus_spadiceus |};
  {| tip_label := "Sciurus_igniventris_SCIURIDAE_RODENTIA"; tip_species := sp Sciurus_igniventris |};
  {| tip_label := "Sciurus_ignitus_SCIURIDAE_RODENTIA"; tip_species := sp Sciurus_ignitus |};
  {| tip_label := "Microsciurus_flaviventer_SCIURIDAE_RODENTIA"; tip_species := sp Microsciurus_flaviventer |};
  {| tip_label := "Sciurus_stramineus_SCIURIDAE_RODENTIA"; tip_species := sp Sciurus_stramineus |};
  {| tip_label := "Sciurus_vulgaris_SCIURIDAE_RODENTIA"; tip_species := sp Sciurus_vulgaris |};
  {| tip_label := "Sciurus_lis_SCIURIDAE_RODENTIA"; tip_species := sp Sciurus_lis |};
  {| tip_label := "Rheithrosciurus_macrotis_SCIURIDAE_RODENTIA"; tip_species := sp Rheithrosciurus_macrotis |};
  {| tip_label := "Tamiasciurus_mearnsi_SCIURIDAE_RODENTIA"; tip_species := sp Tamiasciurus_douglasii |};
  {| tip_label := "Tamiasciurus_hudsonicus_SCIURIDAE_RODENTIA"; tip_species := sp Tamiasciurus_hudsonicus |};
  {| tip_label := "Tamiasciurus_douglasii_SCIURIDAE_RODENTIA"; tip_species := sp Tamiasciurus_douglasii |};
  {| tip_label := "Petaurista_leucogenys_SCIURIDAE_RODENTIA"; tip_species := sp Petaurista_leucogenys |};
  {| tip_label := "Petaurista_lena_SCIURIDAE_RODENTIA"; tip_species := sp Petaurista_lena |};
  {| tip_label := "Petaurista_petaurista_SCIURIDAE_RODENTIA"; tip_species := sp Petaurista_petaurista |};
  {| tip_label := "Petaurista_grandis_SCIURIDAE_RODENTIA"; tip_species := sp Petaurista_grandis |};
  {| tip_label := "Petaurista_caniceps_SCIURIDAE_RODENTIA"; tip_species := sp Petaurista_caniceps |};
  {| tip_label := "Petaurista_albiventer_SCIURIDAE_RODENTIA"; tip_species := sp Petaurista_albiventer |};
  {| tip_label := "Petaurista_yunanensis_SCIURIDAE_RODENTIA"; tip_species := sp Petaurista_nobilis |};
  {| tip_label := "Petaurista_philippensis_SCIURIDAE_RODENTIA"; tip_species := sp Petaurista_philippensis |};
  {| tip_label := "Petaurista_hainana_SCIURIDAE_RODENTIA"; tip_species := sp Petaurista_hainanus |};
  {| tip_label := "Petaurista_alborufus_SCIURIDAE_RODENTIA"; tip_species := sp Petaurista_alborufus |};
  {| tip_label := "Petaurista_elegans_SCIURIDAE_RODENTIA"; tip_species := sp Petaurista_elegans |};
  {| tip_label := "Petaurista_marica_SCIURIDAE_RODENTIA"; tip_species := sp Petaurista_marica |};
  {| tip_label := "Petaurista_xanthotis_SCIURIDAE_RODENTIA"; tip_species := sp Petaurista_xanthotis |};
  {| tip_label := "Aeromys_tephromelas_SCIURIDAE_RODENTIA"; tip_species := sp Aeromys_tephromelas |};
  {| tip_label := "Eupetaurus_cinereus_SCIURIDAE_RODENTIA"; tip_species := sp Eupetaurus_cinereus |};
  {| tip_label := "Aeretes_melanopterus_SCIURIDAE_RODENTIA"; tip_species := sp Aeretes_melanopterus |};
  {| tip_label := "Trogopterus_xanthipes_SCIURIDAE_RODENTIA"; tip_species := sp Trogopterus_xanthipes |};
  {| tip_label := "Belomys_pearsonii_SCIURIDAE_RODENTIA"; tip_species := sp Belomys_pearsonii |};
  {| tip_label := "Pteromyscus_pulverulentus_SCIURIDAE_RODENTIA"; tip_species := sp Pteromyscus_pulverulentus |};
  {| tip_label := "Pteromys_volans_SCIURIDAE_RODENTIA"; tip_species := sp Pteromys_volans |};
  {| tip_label := "Pteromys_momonga_SCIURIDAE_RODENTIA"; tip_species := sp Pteromys_momonga |};
  {| tip_label := "Eoglaucomys_fimbriatus_SCIURIDAE_RODENTIA"; tip_species := sp Eoglaucomys_fimbriatus |};
  {| tip_label := "Hylopetes_nigripes_SCIURIDAE_RODENTIA"; tip_species := sp Hylopetes_nigripes |};
  {| tip_label := "Hylopetes_lepidus_SCIURIDAE_RODENTIA"; tip_species := sp Hylopetes_sagitta |};
  {| tip_label := "Iomys_horsfieldii_SCIURIDAE_RODENTIA"; tip_species := sp Iomys_horsfieldii |};
  {| tip_label := "Hylopetes_spadiceus_SCIURIDAE_RODENTIA"; tip_species := sp Hylopetes_spadiceus |};
  {| tip_label := "Petaurillus_kinlochii_SCIURIDAE_RODENTIA"; tip_species := sp Petaurillus_kinlochii |};
  {| tip_label := "Hylopetes_alboniger_SCIURIDAE_RODENTIA"; tip_species := sp Hylopetes_alboniger |};
  {| tip_label := "Petinomys_setosus_SCIURIDAE_RODENTIA"; tip_species := sp Petinomys_setosus |};
  {| tip_label := "Hylopetes_phayrei_SCIURIDAE_RODENTIA"; tip_species := sp Hylopetes_phayrei |};
  {| tip_label := "Glaucomys_volans_SCIURIDAE_RODENTIA"; tip_species := sp Glaucomys_volans |};
  {| tip_label := "Glaucomys_sabrinus_SCIURIDAE_RODENTIA"; tip_species := sp Glaucomys_sabrinus |}].

Definition upham2019 : tree N :=
 (Fork 1000 3020 2552 3534
  (Fork 435 2742 2214 3251
   (Fork 1000 762 439 1174
    (Tip 0%N)
    (Fork 673 229 0 611
     (Tip 1%N)
     (Tip 2%N)))
   (Tip 3%N))
  (Fork 998 2685 2262 3095
   (Fork 968 2592 2207 3012
    (Fork 1000 2427 2041 2816
     (Fork 1000 2170 1823 2539
      (Fork 802 2087 1758 2445
       (Fork 1000 1561 1256 1869
        (Fork 448 1421 1149 1703
         (Fork 1000 936 607 1293
          (Tip 4%N)
          (Tip 5%N))
         (Fork 821 1163 880 1457
          (Fork 304 309 2 906
           (Tip 6%N)
           (Tip 7%N))
          (Fork 341 717 432 999
           (Fork 564 199 58 359
            (Tip 8%N)
            (Tip 9%N))
           (Fork 222 236 1 669
            (Tip 10%N)
            (Tip 11%N)))))
        (Fork 203 1431 1126 1744
         (Fork 992 793 442 1150
          (Tip 12%N)
          (Tip 13%N))
         (Tip 14%N)))
       (Fork 999 1897 1593 2218
        (Fork 1000 991 778 1208
         (Fork 1000 483 367 591
          (Fork 305 389 285 478
           (Fork 978 289 187 404
            (Fork 1000 154 96 215
             (Fork 999 98 49 154
              (Tip 15%N)
              (Tip 16%N))
             (Fork 972 100 49 150
              (Fork 1000 13 1 29
               (Tip 17%N)
               (Tip 18%N))
              (Tip 19%N)))
            (Tip 20%N))
           (Fork 990 297 211 387
            (Fork 882 239 169 316
             (Fork 934 194 132 259
              (Fork 1000 123 82 171
               (Tip 21%N)
               (Fork 616 103 64 140
                (Fork 549 84 44 124
                 (Tip 22%N)
                 (Tip 23%N))
                (Fork 1000 55 25 88
                 (Fork 999 29 6 54
                  (Tip 24%N)
                  (Tip 25%N))
                 (Tip 26%N))))
              (Tip 27%N))
             (Tip 28%N))
            (Tip 29%N)))
          (Fork 106 408 299 518
           (Fork 1000 131 66 199
            (Tip 30%N)
            (Tip 31%N))
           (Fork 980 356 239 486
            (Fork 805 283 182 388
             (Tip 32%N)
             (Fork 1000 115 67 165
              (Fork 999 69 29 115
               (Tip 33%N)
               (Tip 34%N))
              (Fork 648 89 40 134
               (Tip 35%N)
               (Tip 36%N))))
            (Tip 37%N))))
         (Fork 980 790 610 979
          (Tip 38%N)
          (Tip 39%N)))
        (Fork 1000 1140 920 1362
         (Fork 1000 836 684 994
          (Fork 573 784 640 934
           (Fork 1000 406 313 501
            (Fork 618 340 270 417
             (Fork 385 316 248 390
              (Tip 40%N)
              (Fork 905 282 210 359
               (Fork 999 170 102 244
                (Tip 41%N)
                (Tip 42%N))
               (Tip 43%N)))
             (Fork 532 280 215 348
              (Fork 997 212 151 279
               (Fork 878 179 114 244
                (Tip 44%N)
                (Tip 45%N))
               (Tip 46%N))
              (Fork 500 179 110 256
               (Fork 188 76 3 168
                (Tip 47%N)
                (Tip 48%N))
               (Tip 49%N))))
            (Fork 698 197 129 270
             (Fork 827 156 90 221
              (Tip 50%N)
              (Fork 944 52 17 93
               (Tip 51%N)
               (Tip 52%N)))
             (Tip 53%N)))
           (Fork 999 682 555 819
            (Fork 1000 462 359 564
             (Fork 347 386 269 516
              (Tip 54%N)
              (Tip 55%N))
             (Fork 406 409 325 504
              (Fork 159 376 284 472
               (Fork 984 186 123 249
                (Fork 1000 107 64 153
                 (Tip 56%N)
                 (Fork 996 70 34 107
                  (Fork 1000 25 4 46
                   (Tip 57%N)
                   (Tip 58%N))
                  (Tip 59%N)))
                (Fork 1000 15 0 33
                 (Tip 60%N)
                 (Tip 61%N)))
               (Tip 62%N))
              (Fork 719 328 235 425
               (Tip 63%N)
               (Fork 1000 164 99 234
                (Tip 64%N)
                (Tip 65%N)))))
            (Fork 933 612 498 735
             (Fork 999 520 418 631
              (Fork 755 470 371 576
               (Fork 834 427 331 529
                (Fork 1000 330 246 423
                 (Fork 1000 155 88 223
                  (Tip 66%N)
                  (Tip 67%N))
                 (Fork 1000 135 75 204
                  (Tip 68%N)
                  (Tip 69%N)))
                (Fork 1000 149 94 209
                 (Fork 1000 85 42 132
                  (Tip 70%N)
                  (Fork 1000 32 7 60
                   (Tip 71%N)
                   (Tip 72%N)))
                 (Fork 1000 34 8 65
                  (Tip 73%N)
                  (Tip 74%N))))
               (Tip 75%N))
              (Fork 1000 199 121 283
               (Fork 1000 44 12 83
                (Tip 76%N)
                (Tip 77%N))
               (Tip 78%N)))
             (Fork 1000 432 332 545
              (Fork 874 363 279 448
               (Fork 903 315 237 393
                (Fork 998 216 139 301
                 (Tip 79%N)
                 (Tip 80%N))
                (Fork 993 259 191 334
                 (Tip 81%N)
                 (Fork 501 233 168 302
                  (Tip 82%N)
                  (Fork 998 179 115 242
                   (Fork 1000 77 32 121
                    (Tip 83%N)
                    (Tip 84%N))
                   (Tip 85%N)))))
               (Fork 981 281 199 365
                (Tip 86%N)
                (Fork 1000 99 49 152
                 (Fork 1000 16 1 34
                  (Tip 87%N)
                  (Tip 88%N))
                 (Tip 89%N))))
              (Tip 90%N)))))
          (Fork 1000 617 460 776
           (Fork 1000 241 157 324
            (Fork 1000 168 96 243
             (Tip 91%N)
             (Tip 92%N))
            (Tip 93%N))
           (Fork 1000 253 161 341
            (Fork 601 206 125 287
             (Tip 94%N)
             (Tip 95%N))
            (Tip 96%N))))
         (Fork 978 943 708 1175
          (Fork 1000 184 97 276
           (Tip 97%N)
           (Fork 609 132 59 207
            (Tip 98%N)
            (Tip 99%N)))
          (Fork 1000 475 318 641
           (Tip 100%N)
           (Tip 101%N))))))
      (Tip 102%N))
     (Fork 1000 1771 1435 2118
      (Tip 103%N)
      (Fork 1000 968 699 1240
       (Tip 104%N)
       (Fork 33 901 660 1112
        (Fork 849 614 444 800
         (Tip 105%N)
         (Fork 886 240 143 341
          (Tip 106%N)
          (Tip 107%N)))
        (Tip 108%N)))))
    (Fork 1000 1849 1510 2204
     (Fork 999 1661 1372 1973
      (Fork 998 1477 1216 1745
       (Fork 987 1316 1095 1548
        (Fork 963 963 776 1156
         (Fork 1000 741 579 917
          (Fork 632 646 496 810
           (Fork 997 527 379 684
            (Tip 109%N)
            (Fork 1000 274 170 381
             (Tip 110%N)
             (Tip 111%N)))
           (Tip 112%N))
          (Tip 113%N))
         (Fork 1000 740 578 910
          (Fork 999 612 465 768
           (Tip 114%N)
           (Fork 1000 376 255 495
            (Tip 115%N)
            (Tip 116%N)))
          (Tip 117%N)))
        (Fork 759 1223 1018 1452
         (Fork 999 885 707 1062
          (Fork 999 271 165 379
           (Tip 118%N)
           (Tip 119%N))
          (Fork 391 815 647 982
           (Fork 990 706 532 880
            (Fork 1000 359 239 489
             (Tip 120%N)
             (Tip 121%N))
            (Fork 1000 283 181 393
             (Tip 122%N)
             (Tip 123%N)))
           (Fork 1000 526 349 700
            (Tip 124%N)
            (Tip 125%N))))
         (Fork 721 1120 925 1336
          (Fork 640 1030 835 1234
           (Fork 183 833 649 1022
            (Tip 126%N)
            (Fork 181 600 433 782
             (Fork 159 483 286 678
              (Tip 127%N)
              (Tip 128%N))
             (Fork 11 520 399 666
              (Tip 129%N)
              (Fork 55 190 5 474
               (Tip 130%N)
               (Tip 131%N)))))
           (Fork 148 935 735 1131
            (Fork 333 383 211 628
             (Fork 118 141 2 328
              (Tip 132%N)
              (Tip 133%N))
             (Fork 765 90 44 141
              (Tip 134%N)
              (Fork 904 37 12 64
               (Tip 135%N)
               (Fork 776 22 4 44
                (Tip 136%N)
                (Tip 137%N)))))
            (Fork 68 812 608 1003
             (Fork 489 181 107 257
              (Tip 138%N)
              (Fork 352 139 77 202
               (Tip 139%N)
               (Tip 140%N)))
             (Tip 141%N))))
          (Fork 835 720 467 1014
           (Tip 142%N)
           (Fork 180 581 395 778
            (Tip 143%N)
            (Fork 359 199 1 530
             (Tip 144%N)
             (Tip 145%N)))))))
       (Tip 146%N))
      (Fork 1000 800 491 1124
       (Tip 147%N)
       (Tip 148%N)))
     (Fork 1000 702 375 1041
      (Tip 149%N)
      (Tip 150%N))))
   (Fork 1000 2076 1733 2412
    (Fork 1000 1342 1091 1610
     (Fork 999 1009 809 1220
      (Tip 151%N)
      (Fork 222 962 770 1171
       (Fork 999 709 565 866
        (Fork 1000 316 135 527
         (Tip 152%N)
         (Tip 153%N))
        (Fork 908 631 508 770
         (Fork 892 492 362 634
          (Tip 154%N)
          (Tip 155%N))
         (Fork 871 555 441 680
          (Fork 334 511 401 636
           (Tip 156%N)
           (Fork 998 434 317 543
            (Fork 999 103 10 215
             (Tip 157%N)
             (Tip 158%N))
            (Fork 954 341 234 450
             (Tip 159%N)
             (Fork 1000 13 0 31
              (Tip 160%N)
              (Tip 161%N)))))
          (Fork 1000 448 343 552
           (Fork 897 418 325 529
            (Fork 848 380 287 489
             (Fork 978 52 0 156
              (Tip 162%N)
              (Tip 163%N))
             (Fork 818 303 203 412
              (Tip 164%N)
              (Fork 113 115 0 272
               (Tip 165%N)
               (Tip 166%N))))
            (Tip 167%N))
           (Tip 168%N)))))
       (Fork 637 261 63 735
        (Fork 648 134 70 206
         (Tip 169%N)
         (Tip 170%N))
        (Tip 171%N))))
     (Fork 1000 99 45 162
      (Fork 410 64 18 114
       (Tip 172%N)
       (Tip 173%N))
      (Tip 174%N)))
    (Fork 1000 1694 1395 1975
     (Fork 1000 1530 1270 1806
      (Fork 1000 877 683 1072
       (Tip 175%N)
       (Fork 994 758 593 918
        (Fork 1000 547 404 702
         (Tip 176%N)
         (Fork 995 385 259 516
          (Fork 1000 129 63 198
           (Tip 177%N)
           (Tip 178%N))
          (Tip 179%N)))
        (Fork 984 667 521 827
         (Fork 1000 378 275 486
          (Fork 1000 203 123 285
           (Tip 180%N)
           (Tip 181%N))
          (Fork 1000 222 149 293
           (Fork 680 176 107 247
            (Tip 182%N)
            (Tip 183%N))
           (Tip 184%N)))
         (Fork 1000 327 220 439
          (Tip 185%N)
          (Fork 1000 133 70 204
           (Tip 186%N)
           (Tip 187%N))))))
      (Fork 999 1374 1120 1638
       (Fork 1000 1126 883 1381
        (Fork 998 787 503 1076
         (Tip 188%N)
         (Tip 189%N))
        (Fork 1000 545 338 771
         (Fork 677 430 249 629
          (Fork 1000 163 46 289
           (Tip 190%N)
           (Tip 191%N))
          (Tip 192%N))
         (Tip 193%N)))
       (Fork 1000 516 353 693
        (Tip 194%N)
        (Tip 195%N))))
     (Fork 1000 1279 1041 1533
      (Tip 196%N)
      (Fork 209 1222 995 1469
       (Fork 993 896 700 1095
        (Fork 867 609 421 793
         (Tip 197%N)
         (Fork 562 319 175 489
          (Fork 219 119 0 282
           (Tip 198%N)
           (Tip 199%N))
          (Tip 200%N)))
        (Fork 909 576 410 756
         (Fork 728 198 0 497
          (Tip 201%N)
          (Tip 202%N))
         (Fork 988 360 240 482
          (Tip 203%N)
          (Tip 204%N))))
       (Fork 1000 201 117 289
        (Tip 205%N)
        (Tip 206%N)))))))).
