#!/usr/bin/env python3
"""Generate the Coq data modules in theories/Sciuridae/Data/ from data/.

Standard library only.  Deterministic: running it twice produces identical
files, and CI checks that the committed .v files equal a fresh generation.

  python3 tools/gen_coq.py           # (re)generate
  python3 tools/gen_coq.py --check   # fail if the committed files are stale
"""
import csv, json, math, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'data')
OUT = os.path.join(ROOT, 'theories', 'Data')
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

HEADER = """(******************************************************************************)
(*  GENERATED by tools/gen_coq.py -- do not edit by hand.                     *)
(*  Source: {src:<68}*)
(******************************************************************************)
"""

CONTINENTS = ['Africa', 'Antarctica', 'Asia', 'Europe', 'North America', 'Oceania', 'South America']
REALMS = ['Afrotropic', 'Antarctic', 'Australasia', 'Indomalaya', 'Nearctic', 'Neotropic', 'Oceania', 'Palearctic']
IUCN = ['LC', 'NT', 'VU', 'EN', 'CR', 'EW', 'EX', 'DD', 'NE']
SUBFAMILIES = ['Ratufinae', 'Sciurillinae', 'Sciurinae', 'Nannosciurinae', 'Xerinae']


def ident(name):
    s = re.sub(r'[^0-9A-Za-z]+', '_', name).strip('_')
    if not s or not s[0].isalpha():
        s = 'X_' + s
    return s


def realm_ident(name):
    # The realm 'Oceania' would clash with the continent of the same name.
    return 'Oceanian' if name == 'Oceania' else ident(name)


def coq_string(s):
    return '"' + s.replace('"', '""') + '"'


def coq_list(items, per_line=None, indent='  '):
    if not items:
        return '[]'
    if per_line is None:
        return '[' + '; '.join(items) + ']'
    lines = []
    for i in range(0, len(items), per_line):
        lines.append(indent + '; '.join(items[i:i + per_line]))
    return '[\n' + ';\n'.join(lines) + ']'


def finite_enum(tname, prefix, constrs, names, doc):
    """Inductive type + index + table + Beq/Finite instances + name function."""
    out = [f'(* {doc} *)', f'Inductive {tname} : Type :=']
    out += [f'| {c}' for c in constrs]
    out[-1] += '.'
    out.append('')
    out.append(f'Definition {prefix}_index (x : {tname}) : nat :=')
    out.append('  match x with')
    out += [f'  | {c} => {i}' for i, c in enumerate(constrs)]
    out.append('  end.')
    out.append('')
    out.append(f'Definition {prefix}_table : list {tname} := {coq_list(constrs, 6)}.')
    out.append('')
    out.append(f'Lemma {prefix}_table_index : forall x, nth_error {prefix}_table ({prefix}_index x) = Some x.')
    out.append('Proof. solve_table_index. Qed.')
    out.append('')
    out.append(f'Lemma {prefix}_indices : map {prefix}_index {prefix}_table = seq 0 (List.length {prefix}_table).')
    out.append('Proof. vm_compute. reflexivity. Qed.')
    out.append('')
    out.append(f'#[export] Instance Beq_{tname} : Beq {tname} :=')
    out.append(f'  {{| beq := table_beq {tname} {prefix}_index;')
    out.append(f'     beq_spec := table_beq_spec {tname} {prefix}_index {prefix}_table {prefix}_table_index |}}.')
    out.append('')
    out.append(f'#[export] Instance Finite_{tname} : Finite {tname} :=')
    out.append(f'  {{| enum := {prefix}_table;')
    out.append(f'     enum_complete := table_complete {tname} {prefix}_index {prefix}_table {prefix}_table_index;')
    out.append(f'     enum_nodup := table_nodup {tname} {prefix}_index {prefix}_table {prefix}_indices |}}.')
    out.append('')
    out.append(f'Definition {prefix}_name (x : {tname}) : string :=')
    out.append('  match x with')
    out += [f'  | {c} => {coq_string(n)}' for c, n in zip(constrs, names)]
    out.append('  end.')
    out.append('')
    return '\n'.join(out)


def write(name, text, check, stale):
    path = os.path.join(OUT, name)
    if check:
        old = open(path, encoding='utf-8').read() if os.path.exists(path) else None
        if old != text:
            stale.append(name)
    else:
        os.makedirs(OUT, exist_ok=True)
        with open(path, 'w', encoding='utf-8') as f:
            f.write(text)


# ---------------------------------------------------------------- MDD

def load_mdd():
    with open(os.path.join(DATA, 'mdd', 'MDD_v2.5_Sciuridae.csv'), encoding='utf-8') as f:
        rows = list(csv.DictReader(f))
    rows.sort(key=lambda r: int(r['phylosort']))
    return rows


def split_field(v):
    """MDD pipe lists; a trailing '?' marks an uncertain record."""
    sure, unsure = [], []
    for x in v.split('|'):
        x = x.strip()
        if not x or x == 'NA':
            continue
        (unsure if x.endswith('?') else sure).append(x.rstrip('?').strip())
    return sure, unsure


def gen_geography(rows):
    countries = sorted({c for r in rows for part in split_field(r['countryDistribution']) for c in part})
    for r in rows:
        for c in split_field(r['continentDistribution'])[0] + split_field(r['continentDistribution'])[1]:
            assert c in CONTINENTS, c
        for c in split_field(r['biogeographicRealm'])[0] + split_field(r['biogeographicRealm'])[1]:
            assert c in REALMS, c
    txt = HEADER.format(src='MDD v2.5 vocabularies (continents, realms, IUCN); countries used by Sciuridae')
    txt += """
From Coq Require Import List String.
From Sciuridae Require Import Lib.Base.
Import ListNotations.
Local Open Scope string_scope.

"""
    txt += finite_enum('Continent', 'continent', [ident(c) for c in CONTINENTS], CONTINENTS,
                       'Continents, in the vocabulary of MDD v2.5 (continentDistribution).')
    txt += finite_enum('Realm', 'realm', [realm_ident(c) for c in REALMS], REALMS,
                       'Biogeographic realms, in the vocabulary of MDD v2.5 (biogeographicRealm).')
    txt += finite_enum('Country', 'country', [ident(c) for c in countries], countries,
                       f'The {len(countries)} countries in which MDD v2.5 records a native sciurid.')
    txt += finite_enum('IUCN', 'iucn', IUCN, ['Least Concern', 'Near Threatened', 'Vulnerable', 'Endangered',
                                               'Critically Endangered', 'Extinct in the Wild', 'Extinct',
                                               'Data Deficient', 'Not Evaluated'],
                       'IUCN Red List categories (MDD v2.5 iucnStatus).')
    return txt, countries


def gen_taxonomy(rows):
    genera, gsub, gtri = [], {}, {}
    for r in rows:
        g = r['genus']
        if g not in gsub:
            genera.append(g)
            gsub[g], gtri[g] = r['subfamily'], r['tribe']
        assert gsub[g] == r['subfamily'] and gtri[g] == r['tribe'], f'inconsistent classification in {g}'
    tribes = []
    tsub = {}
    for g in genera:
        t = gtri[g]
        if t == 'NA':
            continue
        if t not in tsub:
            tribes.append(t)
            tsub[t] = gsub[g]
        assert tsub[t] == gsub[g], f'tribe {t} in two subfamilies'
    assert set(gsub.values()) == set(SUBFAMILIES)
    txt = HEADER.format(src='data/mdd/MDD_v2.5_Sciuridae.csv (MDD v2.5, 2026-07-28; CC-BY 4.0)')
    txt += """
From Coq Require Import List String.
From Sciuridae Require Import Lib.Base.
Import ListNotations.
Local Open Scope string_scope.

"""
    txt += finite_enum('Subfamily', 'subfamily', SUBFAMILIES, SUBFAMILIES, 'Subfamilies of Sciuridae (MDD v2.5).')
    txt += finite_enum('Tribe', 'tribe', tribes, tribes, 'Tribes of Sciuridae (MDD v2.5).')
    txt += finite_enum('Genus', 'genus', genera, genera,
                       f'The {len(genera)} genera of Sciuridae recognised by MDD v2.5, in MDD order.')
    txt += '(* The subfamily containing each tribe. *)\n'
    txt += 'Definition tribe_subfamily (t : Tribe) : Subfamily :=\n  match t with\n'
    txt += ''.join(f'  | {t} => {tsub[t]}\n' for t in tribes) + '  end.\n\n'
    txt += ('(* Where a genus sits: in a tribe, or directly in a subfamily that has no\n'
            '   tribes.  Subfamily membership is derived from this, so the ranks nest\n'
            '   by construction. *)\n')
    txt += 'Inductive Placement : Type :=\n| InTribe : Tribe -> Placement\n| InSubfamily : Subfamily -> Placement.\n\n'
    txt += 'Definition genus_placement (g : Genus) : Placement :=\n  match g with\n'
    for g in genera:
        p = f'InTribe {gtri[g]}' if gtri[g] != 'NA' else f'InSubfamily {gsub[g]}'
        txt += f'  | {g} => {p}\n'
    txt += '  end.\n\n'
    return txt, genera, gsub, gtri, tribes


def gen_species(rows, genera, countries):
    txt = HEADER.format(src='data/mdd/MDD_v2.5_Sciuridae.csv (MDD v2.5, 2026-07-28; CC-BY 4.0)')
    txt += """
From Coq Require Import List String NArith.
From Sciuridae Require Import Lib.Base Data.Geography Data.Taxonomy.
Import ListNotations.
Local Open Scope string_scope.

(* Species are indexed by their genus, so a species can never be filed under
   the wrong genus. *)
"""
    names = [r['genus'] + '_' + r['specificEpithet'] for r in rows]
    txt += 'Inductive Species : Genus -> Type :=\n'
    txt += ''.join(f'| {n} : Species {r["genus"]}\n' for n, r in zip(names, rows))
    txt = txt.rstrip('\n') + '.\n\n'
    txt += """Definition AnySpecies : Type := { g : Genus & Species g }.
Definition sp {g : Genus} (s : Species g) : AnySpecies := existT Species g s.
Definition species_genus (s : AnySpecies) : Genus := projT1 s.

Definition species_index (s : AnySpecies) : nat :=
  match s with
  | existT _ _ s' =>
      match s' with
"""
    txt += ''.join(f'      | {n} => {i}\n' for i, n in enumerate(names))
    txt += '      end\n  end.\n\n'
    txt += 'Definition species_table : list AnySpecies := ' + coq_list([f'sp {n}' for n in names], 3) + '.\n\n'
    txt += """Lemma species_table_index : forall s, nth_error species_table (species_index s) = Some s.
Proof. intros [g s]; destruct s; reflexivity. Qed.

Lemma species_indices : map species_index species_table = seq 0 (List.length species_table).
Proof. vm_compute. reflexivity. Qed.

#[export] Instance Beq_AnySpecies : Beq AnySpecies :=
  {| beq := table_beq AnySpecies species_index;
     beq_spec := table_beq_spec AnySpecies species_index species_table species_table_index |}.

#[export] Instance Finite_AnySpecies : Finite AnySpecies :=
  {| enum := species_table;
     enum_complete := table_complete AnySpecies species_index species_table species_table_index;
     enum_nodup := table_nodup AnySpecies species_index species_table species_indices |}.

(* Everything MDD v2.5 records about a species that this development uses.
   Distribution lists are native ranges; [uncertain] lists hold records that
   MDD marks as uncertain. *)
Record SpeciesInfo : Type := {
  epithet : string;
  common_name : string;
  author : string;
  year : nat;
  author_in_parentheses : bool;      (* species originally described in another genus *)
  mdd_id : N;                        (* MDD v2.5 species identifier *)
  iucn : IUCN;
  iucn_note : string;                (* name under which IUCN assessed it, if different *)
  countries : list Country;
  countries_uncertain : list Country;
  continents : list Continent;
  realms : list Realm;
  realms_uncertain : list Realm
}.

"""
    recs = []
    for n, r in zip(names, rows):
        cs, cu = split_field(r['countryDistribution'])
        ks, ku = split_field(r['continentDistribution'])
        rs, ru = split_field(r['biogeographicRealm'])
        assert not ku, n
        status = r['iucnStatus'].strip()
        m = re.match(r'^(LC|NT|VU|EN|CR|EW|EX|DD|NE)(?:\s*\((.*)\))?$', status)
        assert m, status
        year = int(r['authoritySpeciesYear'])
        rec = f'  (* {n} *)\n  {{|'
        rec += f' epithet := {coq_string(r["specificEpithet"])}; common_name := {coq_string(r["mainCommonName"])};\n'
        rec += f'     author := {coq_string(r["authoritySpeciesAuthor"])}; year := {year}; '
        rec += f'author_in_parentheses := {"true" if r["authorityParentheses"] == "1" else "false"};\n'
        rec += f'     mdd_id := {int(r["id"])}%N; iucn := {m.group(1)}; iucn_note := {coq_string(m.group(2) or "")};\n'
        rec += f'     countries := {coq_list([ident(c) for c in cs])};\n'
        rec += f'     countries_uncertain := {coq_list([ident(c) for c in cu])};\n'
        rec += f'     continents := {coq_list([ident(c) for c in ks])};\n'
        rec += f'     realms := {coq_list([realm_ident(c) for c in rs])}; realms_uncertain := {coq_list([realm_ident(c) for c in ru])} |}}'
        recs.append(rec)
    txt += '(* One record per species, in the order of [species_table]. *)\n'
    txt += 'Definition info_table : list SpeciesInfo := [\n' + ';\n'.join(recs) + '].\n\n'
    txt += """(* Placeholder for out-of-range indices; unreachable (see info_table_covers). *)
Definition no_info : SpeciesInfo :=
  {| epithet := ""; common_name := ""; author := ""; year := 0; author_in_parentheses := false;
     mdd_id := 0%N; iucn := NE; iucn_note := ""; countries := []; countries_uncertain := [];
     continents := []; realms := []; realms_uncertain := [] |}.

Definition info (s : AnySpecies) : SpeciesInfo := nth (species_index s) info_table no_info.

Lemma info_table_covers : List.length info_table = List.length species_table.
Proof. vm_compute. reflexivity. Qed.

Lemma info_table_index (s : AnySpecies) : species_index s < List.length info_table.
Proof.
  rewrite info_table_covers; apply nth_error_Some.
  rewrite species_table_index; discriminate.
Qed.

"""
    txt += 'Definition species_name (s : AnySpecies) : string := genus_name (species_genus s) ++ " " ++ epithet (info s).\n'
    return txt, names


# ---------------------------------------------------------------- Upham 2019

def parse_newick(s):
    """Minimal parser for the extract written by tools/extract_sources.py."""
    pos = 0

    def node():
        nonlocal pos
        if s[pos] == '(':
            pos += 1
            kids = [node()]
            while s[pos] == ',':
                pos += 1
                kids.append(node())
            assert s[pos] == ')'
            pos += 1
            m = re.compile(r'\[&posterior=([0-9.eE+-]+),height=([0-9.eE+-]+),hpd=([0-9.eE+-]+):([0-9.eE+-]+)\]').match(s, pos)
            assert m, s[pos:pos + 60]
            pos = m.end()
            return ('node', float(m.group(1)), float(m.group(2)), kids, float(m.group(3)), float(m.group(4)))
        m = re.compile(r'[A-Za-z0-9_]+').match(s, pos)
        pos = m.end()
        return ('tip', m.group(0))

    t = node()
    assert s[pos] == ';'
    return t


def gen_upham(names):
    tree = parse_newick(open(os.path.join(DATA, 'upham2019', 'Sciuridae_DNAonly_MCC.nwk')).read().strip())
    with open(os.path.join(DATA, 'upham2019', 'tip_map.csv'), encoding='utf-8') as f:
        tipmap = {r['tip_label']: r for r in csv.DictReader(f)}
    order = []

    def collect(t):
        if t[0] == 'tip':
            order.append(t[1])
        else:
            for k in t[3]:
                collect(k)
    collect(tree)
    index = {lab: i for i, lab in enumerate(order)}
    nameset = set(names)

    def emit(t, depth):
        pad = ' ' * depth
        if t[0] == 'tip':
            return f'{pad}(Tip {index[t[1]]}%N)'
        _, post, height, kids, lo, hi = t
        assert len(kids) == 2, 'expected a binary tree'
        permille = int(post * 1000 + 1e-9)          # rounded down: never overstates support
        centima = int(round(height * 100))
        lo_c, hi_c = math.floor(lo * 100), math.ceil(hi * 100)   # HPD widened outward to 0.01 Ma
        return (f'{pad}(Fork {permille} {centima} {lo_c} {hi_c}\n' + emit(kids[0], depth + 1) + '\n' +
                emit(kids[1], depth + 1) + ')')

    txt = HEADER.format(src='data/upham2019/Sciuridae_DNAonly_MCC.nwk (Upham et al. 2019, PLoS Biol.)')
    txt += """(*  Sciurid subtree of the DNA-only, topology-free, node-dated maximum clade  *)
(*  credibility tree of Upham, Esselstyn and Jetz (2019), Inferring the       *)
(*  mammal tree, PLoS Biology 17(12): e3000494.  Internal nodes carry the     *)
(*  posterior probability (per mille, rounded down), the node height and its *)
(*  95% HPD interval (widened outward), all in units of 0.01 Ma.  Tips are    *)
(*  numbered (as N) left to right; each is mapped to the MDD v2.5 species it  *)
(*  now belongs to (data/upham2019/tip_map.csv).                              *)
(******************************************************************************)

From Coq Require Import List String NArith.
From Sciuridae Require Import Lib.Base Phylo.Tree Data.Taxonomy Data.Species.
Import ListNotations.
Local Open Scope string_scope.

Record TipInfo : Type := { tip_label : string; tip_species : AnySpecies }.

"""
    entries = []
    for lab in order:
        target = tipmap[lab]['mdd_v2_5_species']
        assert target in nameset, target
        entries.append(f'{{| tip_label := {coq_string(lab)}; tip_species := sp {target} |}}')
    txt += 'Definition tips : list TipInfo := ' + coq_list(entries, 1) + '.\n\n'
    txt += 'Definition upham2019 : tree N :=\n' + emit(tree, 1) + '.\n'
    return txt, len(order)


# ---------------------------------------------------------------- fossils

MATERIAL = {'skeleton': 'Skeleton', 'skull_and_teeth': 'SkullAndTeeth',
            'teeth_and_limb_bones': 'TeethAndLimbBones', 'teeth': 'TeethOnly'}


def opinion(op, tribes):
    if op == 'stem':
        return 'Stem'
    if op == 'incertae_sedis':
        return 'IncertaeSedis'
    kind, _, name = op.partition(':')
    assert name in SUBFAMILIES or name in tribes, op
    return {'subfamily': f'InSubfamilyOp {name}', 'tribe': f'InTribeOp {name}',
            'stem_tribe': f'StemOfTribe {name}'}[kind]


def gen_fossils(tribes):
    with open(os.path.join(DATA, 'fossils.json'), encoding='utf-8') as f:
        d = json.load(f)
    names = list(d['genera'])
    txt = HEADER.format(src='data/fossils.json (sourced literature record; see its evidence fields)')
    txt += """
From Coq Require Import List String.
From Sciuridae Require Import Lib.Base Data.Geography Data.Taxonomy.
Import ListNotations.
Local Open Scope string_scope.

(* Fossil genera are a separate type: they are not part of the MDD species
   list, and nothing about extant squirrels is inferred from them. *)
"""
    txt += finite_enum('FossilGenus', 'fossil', names, names, 'Fossil sciurid genera.')
    txt += """Inductive Material : Type := Skeleton | SkullAndTeeth | TeethAndLimbBones | TeethOnly.

(* A published opinion on where a fossil genus belongs. *)
Inductive Opinion : Type :=
| Stem                          (* outside crown Sciuridae *)
| IncertaeSedis                 (* in Sciuridae (crown or stem), unplaced *)
| InSubfamilyOp : Subfamily -> Opinion
| InTribeOp : Tribe -> Opinion
| StemOfTribe : Tribe -> Opinion.  (* on the lineage leading to a tribe *)

(* Ages are in units of 0.01 Ma, written (youngest, oldest). *)
Record FossilInfo : Type := {
  type_species : string;
  fossil_continents : list Continent;
  material : Material;
  gliding_evidence : bool;
  genus_range : nat * nat;          (* first to last appearance *)
  oldest_dated : nat * nat;         (* the oldest reliably dated occurrence *)
  placements : list (Opinion * string)
}.

Definition fossil_info (f : FossilGenus) : FossilInfo :=
  match f with
"""
    for g in names:
        v = d['genera'][g]
        rng, old = v['genus_range_ma'], v['oldest_dated']
        cent = lambda x: int(round(x * 100))
        pls = '; '.join(f'({opinion(p["opinion"], tribes)}, {coq_string(p["source"])})' for p in v['placements'])
        txt += (f'  | {g} => {{| type_species := {coq_string(v["type_species"])};\n'
                f'      fossil_continents := {coq_list([ident(c) for c in v["continents"]])}; '
                f'material := {MATERIAL[v["material"]]}; gliding_evidence := {"true" if v["gliding_evidence"] else "false"};\n'
                f'      genus_range := ({cent(rng["min"])}, {cent(rng["max"])}); '
                f'oldest_dated := ({cent(old["min_ma"])}, {cent(old["max_ma"])});\n'
                f'      placements := [{pls}] |}}\n')
    txt += '  end.\n'
    return txt


def main():
    check = '--check' in sys.argv
    stale = []
    rows = load_mdd()
    geo, countries = gen_geography(rows)
    write('Geography.v', geo, check, stale)
    tax, genera, gsub, gtri, tribes = gen_taxonomy(rows)
    write('Taxonomy.v', tax, check, stale)
    spe, names = gen_species(rows, genera, countries)
    write('Species.v', spe, check, stale)
    uph, ntips = gen_upham(names)
    write('Upham2019.v', uph, check, stale)
    write('Fossils.v', gen_fossils(tribes), check, stale)
    try:
        import gen_characters
        for fname, text in gen_characters.generate(DATA, genera, rows, HEADER):
            write(fname, text, check, stale)
    except ModuleNotFoundError as e:
        if e.name != 'gen_characters':
            raise
    if check:
        if stale:
            sys.exit('stale generated files: ' + ', '.join(stale))
        print('generated files are up to date')
    else:
        print(f'{len(genera)} genera, {len(tribes)} tribes, {len(names)} species, '
              f'{len(countries)} countries, {ntips} tree tips')


if __name__ == '__main__':
    main()
